### ISSUE TITLE
Documentation is being improperly recognized as code on GitHub

### ISSUE THREAD

**Issue by EzraBrooks** [nasa/cFE#1]
Hi Flight Software folks!
First off, great to see the project is finally being hosted somewhere other than SourceForge! I noticed that because of all of the documentation present in the repository, GitHub is falsely identifying the project as HTML-based. For [my university project's fork of cFE](https://github.com/CACTUS-Mission/cFE), we edited our [.gitattributes](https://github.com/CACTUS-Mission/cFE/blob/master/.gitattributes) to tell GitHub's linguist software to interpret .htm, .html, and .css files in this project as being part of the documentation. This should give the repository the proper language statistics.

**Comment by jcmarsh** [comment]
Thanks, this is helpful!

I'm not sure of the best way to deal with the .prc files (Assist procedures, listed as plsql). Hmm... looks like I also forgot the .css line... Once I have a final .gitattributes file I'll update all of the other cFS apps and close this issue.
