### ISSUE TITLE
submodule updates fail

### ISSUE THREAD

**Issue by nickcounts** [nasa/cFE#10]
While attempting to build this project, the submodule update process fails on `GFS_CI.git`

```
Cloning into 'apps/ci'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:nasa/CFS_CI.git' into submodule path 'apps/ci' failed
```

It looks like the recent [ commit in .gitmodules  ](https://github.com/nasa/cFE/commit/edc14ceb428989b1f183d19027b9d28a29cf96cc)  added new apps and used ssh instead of HTTPS. I presume changing them to the form of

```
[submodule "apps/to"]
	path = apps/to
	url = https://github.com/nasa/CFS_TO.git
[submodule "apps/ci"]
	path = apps/ci
	url = https://github.com/nasa/CFS_CI.git
[submodule "apps/io_lib"]
	path = apps/io_lib
	url = https://github.com/nasa/CFS_IO_LIB.git
``` 

will prevent this issue for others.

**Comment by the-other-james** [comment]
Thanks for the catch!
