### ISSUE TITLE
Documentation/usage mismatch in CFE ES "Start App" command

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#1004]
**Describe the bug**
The `CFE_PLATFORM_ES_DEFAULT_STACK_SIZE` is documented as being a default stack size, not a minimum stack size.  But the CFE ES "Start App" command enforces it as a minimum value here:

https://github.com/nasa/cFE/blob/9804b59eb34154b10bb2946bde7654f3d27f4b85/fsw/cfe-core/src/es/cfe_es_task.c#L900-L906

But this is not in agreement with how it is documented:

https://github.com/nasa/cFE/blob/9804b59eb34154b10bb2946bde7654f3d27f4b85/cmake/sample_defs/cpu1_platform_cfg.h#L1186-L1201

**To Reproduce**
N/A

**Expected behavior**
Should not enforce the default as a minimum.  

I don't see any CFE platform definition for an enforced minimum stack size.  If I remember correctly this was discussed once or twice and the agreement was that this is an operational issue - stack size requirements depend on the app stack usage and the memory constraints of the platform - so CFE cannot (and should not) impose some random limitations on it - it should attempt to do what the user requested.

So recommendation would be to remove this check.
One valid possibility is that if the stack size is specified as 0 (which is definitely not valid), to use the default value instead.

**System observed on:**
Ubuntu 20.04

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment]
> One valid possibility is that if the stack size is specified as 0 (which is definitely not valid), to use the default value instead.

I like this, agreed on don't force as min.
