### ISSUE TITLE
cFE_ES Commands that do not increment the Error Counter when an error occurs

### ISSUE THREAD

**Issue by wmoleski** [nasa/cFE#1005]
While testing Bootes on VxWorks, I issued the following commands that generated an Error Event but did not increment the ES CMDEC counter: SCX_CPU1_ES_WRITEERLOG2FILE and SCX_CPU1_ES_STOPPERF.

**To Reproduce**
1. Issue the command SCX_CPU1_ES_WRITEERLOG2FILE ERLOGFILENAME="nopathname.log"
2. Error Event ID=56 is generated but the ES.CMDPC is not incremented
3. Issue the SCX_CPU1_ES_STOPPERF DATAFILENAME="nopathname"
4. Debug EID=60 is generated which makes me think the command was accepted as valid.
5. Also, Error Event ID=67 is generated but again the CMDEC did not increment,

**Expected behavior**
cFE 6.7.0 testing incremented the CMDEC for these 2 cases.

**System observed on:**
 - MCP750 running VxWorks 6.9. cFE Version 6.7.99.0 OSAL 5.0.99.0

Walt Moleski/GSFC 582
[scx_cpu1_es_logging-2020-311-12h27m15s.log](https://github.com/nasa/cFE/files/5501974/scx_cpu1_es_logging-2020-311-12h27m15s.log)

**Comment by skliper** [comment]
This happens because the file is now opened in the background task so it's reported as an error from that context.  This pattern is not unique to this command, there's others that can fail in later processing, while the command counter is still incremented.  Closing as-is (test should be updated).
