### ISSUE TITLE
Version string not reported correctly

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1080]
**Is your feature request related to a problem? Please describe.**
`EVS Port1 66/1/CFE_ES 2: cFS Versions: cfe v6.8.0-rc1+dev236, osal v5.1.0-rc1+dev149, psp v1.5.0-rc146. cFE chksm 52385`

Note missing `+dev` for psp

**Describe the solution you'd like**
add `+dev`

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
Issue moved to [nasa/PSP #241](https://github.com/nasa/PSP/issues/241) via [**ZenHub**](https://www.zenhub.com/)
