### ISSUE TITLE
cfe_sb.h -- #if instead of #ifdef CFE_OMIT_DEPRECATED_6_8

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/cFE#1081]
Probable typo?

https://github.com/nasa/cFE/blob/1ede295c3874e6571aca965a7850d950cf7aa1a3/fsw/cfe-core/src/inc/cfe_sb.h#L649

**Comment by skliper** [comment]
also found one in cfe _sb_api.c... I'll fix.
