### ISSUE TITLE
Update CRC Algorithm Documentation

### ISSUE THREAD

**Issue by mjmccaskey** [nasa/cFE#1094]
**Is your feature request related to a problem? Please describe.**
It would be useful to update the documentation in CFE_ES_CalculateCRC function to include information on the CRC algorithms used, specifically CRC-16 as that is currently the only one implemented.

**Describe the solution you'd like**
Include the following information that describes the CRC16 algorithm
- Name: CRC-16/ARC
- Polynomial: 0x8005
- Initialization: 0x0000
- Reflect Input/Output: true
- XorOut: 0x0000

**Additional context**
While the specific algorithm has several aliases (some listed here https://reveng.sourceforge.io/crc-catalogue/16.htm) this at least provides enough information for one to recreate the lookup table/perform their own sanity checks on the CRC calculations.

**Requester Info**
Mathew McCaskey
HX5 / NASA-GRC
Regenerative Fuel Cell Project

**Comment by skliper** [comment]
See also nasa/tblCRCTool#30
