### ISSUE TITLE
Consider simplifying the zero-copy SB API

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#1155]
**Is your feature request related to a problem? Please describe.**
After some refactoring in PR #1154 the whole `CFE_SB_ZeroCopyHandle_t` has become somewhat extraneous - there is no extra handle/descriptor for a zero copy buffer - they are all the same, and this simply refers to the same buffer descriptor now.

**Describe the solution you'd like**
The API can be simplified and this extra handle removed.  The buffer content pointer is good enough to reconstitute the descriptor  pointer (fixed offset).

**Describe alternatives you've considered**
Leave API as is (backward compatible, just a little more complex than it needs to be).

**Additional context**
This will affect public APIs - CFE_SB_ZeroCopyGetPtr, CFE_SB_ZeroCopyReleasePtr, CFE_SB_TransmitBuffer.  (CFE_SB_ZeroCopySend and CFE_SB_ZeroCopyPass are affected but already deprecated).

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment]
I'd like to fit this in Caelum if we can, lower priority than the rest but a goal.
