### ISSUE TITLE
ES Globals need cleanup

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#1181]
**Is your feature request related to a problem? Please describe.**
The ES core app is quite disorganized in terms of its internal headers (what defines what) and global data structures.  In particular there are three global data objects in this module.

https://github.com/nasa/cFE/blob/c708d64bf2b25500cd0308a700aa4ee0b3fd5909/fsw/cfe-core/src/es/cfe_es_task.h#L148
https://github.com/nasa/cFE/blob/c708d64bf2b25500cd0308a700aa4ee0b3fd5909/fsw/cfe-core/src/es/cfe_es_global.h#L161
https://github.com/nasa/cFE/blob/c708d64bf2b25500cd0308a700aa4ee0b3fd5909/fsw/cfe-core/src/es/cfe_es_global.h#L166

**Describe the solution you'd like**
Make a single `CFE_ES_Global` object as was done for other apps in PR #1124.  Further clean up/re-org the internal headers to create a more logical/consistent content would be nice.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment]
Just a guess - probably not all cleared at initialization either?  Good catch, adding to the Caelum target.

**Comment by jphickey** [comment]
I can do this but since it involves files I'm already moving around in #972 -- I need to postpone/defer until after that one is done (i.e. one re-org at a time).

**Comment by jphickey** [comment]
And yes, looks like `CFE_ES_Global` is actively cleared, the task data is not.
