### ISSUE TITLE
Infinite loop false alarm in unit test (easy fix) - static analysis warning

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1184]
**Is your feature request related to a problem? Please describe.**
Static analysis warning on `i` being int8.  Can be avoided if defined as size_t.
https://github.com/nasa/cFE/blob/c708d64bf2b25500cd0308a700aa4ee0b3fd5909/fsw/cfe-core/unit-test/ut_support.c#L82-L90

Based on logic strlen(UT_subsys) will never be bigger than int8 (unless someone redefines UT_subsys as something unreasonable) so this is a false alarm but easy to fix and better pattern to follow.

**Describe the solution you'd like**
Change to size_t

**Describe alternatives you've considered**
None

**Additional context**
Please wait until #972 is resolved.

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by himanshu007-creator** [comment]
I would like to work on this issue.

**Comment by himanshu007-creator** [comment]
@skliper Hi, as #972 is closed, so i assume it is resolved. So should i go for a PR for this issue?

**Comment by skliper** [comment]
@himanshu007-creator Yes please!  You'll need to follow the PR template instructions to fill out and deliver a CLA before the PR can be merged.  Thanks!
