### ISSUE TITLE
EVS_GenerateEventTelemetry doesn't handle vsnprintf error cases

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1195]
**Is your feature request related to a problem? Please describe.**
vsnprintf can return negative error values, but is compared to unsigned int to handle truncation:
https://github.com/nasa/cFE/blob/672b2dc4f76aa8535eb6b327b73f273c4cf87bb5/fsw/cfe-core/src/evs/cfe_evs_utils.c#L414-L417

I wouldn't call this a bug (will just pass the initialized to zero string), but might be worth a unique message?

**Describe the solution you'd like**
Explicitly handle failure (and cast for comparison)

**Describe alternatives you've considered**
Place termination character at the start? Any other way to provide clues.

**Additional context**
Static analysis warning for coercion alters value.

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by skliper** [comment]
Looking for opinions - could just cast sizeof to (int) which wouldn't do anything (message would still be empty, which is current behavior), could write something unique to message, could do an additional debug event (recursion), could write to the system log... simple "cFE_EVS_SendEvent vsnprintf error %d", or strerror(errno), or explain_vsnprintf().

**Comment by jphickey** [comment]
It wouldn't hurt to first test for a negative result before the truncation test at line 417.  This way it will be ensured that the truncation test does not implicitly do a sign conversion.

As far as what to do -- it really shouldn't fail -- so anything is highly unlikely to occur.  Perhaps a WriteToSyslog, but that uses the same function (I think).  Just return early and skip the rest maybe?
