### ISSUE TITLE
POSIX: Your queue depth may be too large

### ISSUE THREAD

**Issue by aFunnyBit** [nasa/cFE#12]
Update documentation to show Posix fix:

Edit /etc/sysctl.conf and add the lines:

```bash
	# Increase message queue
	fs.mqueue.msg_max = 256
```

## Or 

Edit as root  `/proc/sys/fs/mqueue/msg_max` is set to 256 or some value appropriate.

```bash
root# echo 256 > /proc/sys/fs/mqueue/msg_max
```

**Comment by skliper** [comment]
Due to refactoring repos, added comment at https://github.com/nasa/cFS/blob/rc-6.6.0a/README.md

Will get pushed to master once bundle completes testing.
