### ISSUE TITLE
Possible negative char to isspace - static analysis warning

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1208]
**Is your feature request related to a problem? Please describe.**
In theory a negative value could reach this code through public APIs, which would lead to undefined isspace behavior as it gets converted to int.
https://github.com/nasa/cFE/blob/672b2dc4f76aa8535eb6b327b73f273c4cf87bb5/fsw/cfe-core/src/es/cfe_es_syslog.c#L432

**Describe the solution you'd like**
Recommended practice is to cast to `unsigned char`, such that the conversion to `int` results in defined behavior.

**Describe alternatives you've considered**
Could adjust all the parameters involved to `unsigned char`, but probably not worth it.

**Additional context**
Static analysis warning

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
I went back to the docs on this function, and it says this:

    The  c  argument is an int, the value of which the application shall ensure is a character representable as an
    unsigned char or equal to the value of the macro EOF. If the argument has any other value, the behavior is un‐
    defined.

.... suggests that we actually should cast to `unsigned char` rather than `int` when using any of the ctype checks.
