### ISSUE TITLE
Update directory diagrams in application developer guide

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#1216]
**Is your feature request related to a problem? Please describe.**
After PR #1203 the directory structure diagrams in the user guide are in need of an update.  Only the text was updated in that PR.

**Describe the solution you'd like**
Diagrams should be updated to match the text.

**Additional context**
See #1203

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment]
Note I'd be fine with dropping pictures and using a simpler layout.

**Comment by jphickey** [comment]
The other option is to just copy/paste the output of a `tree -d` command (which is what I put into previous comments).

Fast and easy to update when needed, way easier than graphics....

**Comment by skliper** [comment]
> `tree -d`

Perfect.
