### ISSUE TITLE
Do not rely on OSAL SOFTWARE_(BIG|LITTLE)_BIT_ORDER

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#1217]
**Is your feature request related to a problem? Please describe.**
These endian-indicator macros are problematic for many reasons as documented in nasa/osal#843.  The continued presence of these macros in OSAL came up again in a recent code review.

OSAL will likely stop providing these macros in the next version, because nothing in OSAL is endian-dependent.

CFE only uses these to implement CFE_MAKE_BIG16 / CFE_MAKE_BIG32 macros.

**Describe the solution you'd like**
Move the nonstandard logic from OSAL into CFE, because nothing in OSAL depends on it.

For backward compatibility CFE will likely still have to provide this macro for historical reasons, in case some apps use it, and because TIME uses those CFE_MAKE_BIG* macros.

**Additional context**
See nasa/osal#843

In CFE the logic should be put in a separate header where it can be confined/limited to the scopes where this is actually used/needed, rather than a ubiquitous header like `common_types.h`.  This way an `#error` directive if the check was inconclusive will make more sense since it won't error out on cases where we don't care (i.e. most).

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment]
Could be part of #1209
