### ISSUE TITLE
Entry Point function name too long

### ISSUE THREAD

**Issue by zanzaben** [nasa/cFE#1223]
**Describe the bug**
When trying to run the cfe test runner I got this error 

1980-012-14:03:20.46280 ES Startup: Loading file: /cf/cfe_testrunner.so, APP: TESTRUN_APP
OS_GenericSymbolLookup_Impl():118:Error: CFE_TestRunner_AppM: ./cf/cfe_testrunner.so: undefined symbol: CFE_TestRunner_AppM
1980-012-14:03:20.46306 ES Startup: Could not find symbol:CFE_TestRunner_AppM. EC = 0xFFFFFFFF

It should be trying to use CFE_TestRunner_AppMain but is getting truncated at 19 characters. 
When I shortened the function name it worked fine. 

**To Reproduce**
1. add the start test scripts for the startup test. [Found Here](https://github.com/nasa/cFE/blob/2b8844871d374219cef7c0026e6c43460e11b22b/docs/README_functionaltest.md)
2. Start it. 

**Expected behavior**
It should run the tests. 

**System observed on:**
Ubuntu 20.04

**Reporter Info**
Alex Campbell GSFC

**Comment by zanzaben** [comment]
@jphickey should CFE_TestRunner_AppMain be shortened to something like CFE_TestRunner_AM or should it be able to work with function names longer than 19 characters?

**Comment by jphickey** [comment]
Since AppMain suffix is used elsewhere (sample apps, LAB apps, etc), how about `CFETR_AppMain`?

**Comment by skliper** [comment]
I like CFE_TR_AppMain since it's provided by CFE

**Comment by zanzaben** [comment]
I think CFE_TR_AppMain is the most consistent with other function names.
