### ISSUE TITLE
Duplicate Function in Readme

### ISSUE THREAD

**Issue by ArielSAdamsNASA** [nasa/cFE#1277]
**Describe the bug**
In the version history of the readme, it states: 
> Removes the now-unnecessary CFE_SB_ZeroCopyHandle_t type and all APIs that refer or require it .Replaces CFE_SB_ZeroCopyGetPtr() and CFE_SB_ZeroCopyGetPtr() with two new simplified functions CFE_SB_AllocateMessageBuffer() and CFE_SB_ReleaseMessageBuffer() , respectively. These new functions do not use a separate handle. Updates the CFE_SB_TransmitBuffer() API to also remove the handle. Does affect public APIs. 

The issue is that the version history is stating that the same function, CFE_SB_ZeroCopyGetPtr, is being replaced by two different functions. 

In reality, CFE_SB_ZeroCopyGetPtr was replaced by CFE_SB_AllocateMessageBuffer. CFE_SB_ZeroCopyReleasePtr and CFE_SB_ZeroCopySend, not CFE_SB_ZeroCopyGetPtr, was replaced by CFE_SB_ReleaseMessageBuffer.  

**Expected behavior**
State that CFE_SB_ZeroCopyReleasePtr and CFE_SB_ZeroCopySend, not CFE_SB_ZeroCopyGetPtr, was replaced by CFE_SB_ReleaseMessageBuffer. 

**Code snips**
https://github.com/nasa/cFE/pull/1257/files 

**Reporter Info**
Ariel Adams, ASRC Federal

**Comment by skliper** [comment]
Note `CFE_SB_ZeroCopySend` was replaced by `CFE_SB_TransmitBuffer`.  `CFE_SB_ZeroCopyReleasePtr` was replaced by `CFE_SB_ReleaseMessageBuffer`.

**Comment by astrogeco** [comment]
Good catch, I think this was a copy paste error from a typo in the original PR.

**Comment by astrogeco** [comment]
Just fixed it in the comments for #1257 and #1258. Created a new PR, https://github.com/nasa/cFE/pull/1278, to fix it.
