### ISSUE TITLE
Add cFE Time Current Time API functional tests

### ISSUE THREAD

**Issue by zanzaben** [nasa/cFE#1298]
**Is your feature request related to a problem? Please describe.**
Need open source functional tests for certifiability

**Describe the solution you'd like**
Add functional tests for cFE Time APIs
– CFE_TIME_GetTime
– CFE_TIME_GetTAI
– CFE_TIME_GetUTC
– CFE_TIME_GetMET
– CFE_TIME_GetMETseconds
– CFE_TIME_GetMETsubsecs

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requester Info**
Alex Campbell GSFC

**Comment by astrogeco** [comment]
@zanzaben can you fix typo in issue description? It is referencing the "file header" API instead of TIME.
