### ISSUE TITLE
Could not find the directory ../cfe/inc

### ISSUE THREAD

**Issue by aogrcs** [nasa/cFE#13]
In each app directory, such as sample_app/fsw/for_build/Makefile, there is "-I../cfe/inc", but I could find this sub directory in cFE/build/cpu1/cfe, where I can get sample_app int the directory /cFE/build/cpu1. Thanks!
Sincerely

**Comment by skliper** [comment]
https://coreflightsystem.org/ has links to submit bugs or contact the cFS community for support if the issue still persists.
