### ISSUE TITLE
Remove `extern` from function prototypes

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1319]
**Is your feature request related to a problem? Please describe.**
Inconsistently applying extern to function prototypes

**Describe the solution you'd like**
Remove, it makes no difference.

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by himanshu007-creator** [comment]
I would like to work on this issue. Please guide me further

**Comment by pavll** [comment]
@skliper 

I have removed all `extern` from all function prototypes in the project. Could this cause unforeseen problems (in conjunction with the cFS)?

**Comment by skliper** [comment]
Not for the function prototypes, declaring as `extern` has no impact since it's the default. https://stackoverflow.com/questions/27447285/extern-on-function-prototypes.  Thanks for the contribution!

**Comment by pavll** [comment]
Ok, great to know.
