### ISSUE TITLE
Add null pointer check to CFE_ES_ReloadApp functional test

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1324]
**Is your feature request related to a problem? Please describe.**
AppFIleName NULL not checked (or tested)
https://github.com/nasa/cFE/blob/e80aae94e0f56b868657daba965c590766a4dc57/modules/es/fsw/src/cfe_es_api.c#L220-L226

**Describe the solution you'd like**
Add a NULL test, add the check (if needed)

**Describe alternatives you've considered**
None

**Additional context**
Code review

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by zanzaben** [comment]
AppFileName is tested for null inside OS_stat which is the first place to use it.

**Comment by skliper** [comment]
Switched to unit-test only, since just the functional check is needed for the NULL pointer.

**Comment by zanzaben** [comment]
This will be covered by #806
