### ISSUE TITLE
CFE_ES_RegisterCDSEx: clear block if new allocation is needed but not new block size

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1337]
**Is your feature request related to a problem? Please describe.**
May need to clear block if a new allocation is needed without a changed block size
https://github.com/nasa/cFE/blob/e80aae94e0f56b868657daba965c590766a4dc57/modules/es/fsw/src/cfe_es_cds.c#L383

**Describe the solution you'd like**
Analyze, clear block if needed

**Describe alternatives you've considered**
If not needed, document why for future reference

**Additional context**
Code review

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
Looked into this code, its one of those areas where the original design appears to have evolved in a certain way, and so the "classic" behavior from old CFE versions was preserved.

I went back to the requirements to see what it says, and only these three:

cES1315 | Upon receipt of a Request, the cFE shall reserve the Request specified amount of memory in the Critical Data Store for the cFE Application using the Request specified name.
-- | --
cES1315.1 | If a Critical Data Store exists for the Request specified name but has a different size than what is specified in the Request, the cFE shall remove the existing Critical Data Store and create a new one using the Request specified name and size.
cES1315.2 | If a Critical Data Store exists for the Request specified name but the Data Integrity value is invalid, the cFE shall remove the existing Critical Data Store and create a new one using the Request specified name and size.

But none of these requirements say anything about "pre-clearing" the CDS block, and historically the code has _not_ done this in either case (i.e. for new allocations or size changes).  I can't say for sure why not, but most likely for two reasons:
 - CDS access might be slow (e.g. flash/eeprom memory, possibly indirectly accessed through an of intermediate serial link) so zeroing it out could take a fair bit of time.
 - CDS memory might have a limited number of write cycles and zeroing it out might reduce its lifespan
 - CDS blocks are protected by a CRC-32.  So in the event that a user attempted to read a CDS that had never been written to, it would fail the CRC check and the user would get `CFE_ES_CDS_BLOCK_CRC_ERR`.  Notably this _is_ dependent on the size of the block too, so if the block size were to change, even if it had a previous content with a good CRC, the CRC check would likely fail fo the new/different block size.

My recommendation is to leave this as is, for the reasons above.  Changing behavior is likely to have unintended side effects.
