### ISSUE TITLE
Move `Name` to the end of `CFE_ES_CD_RegRec_t` to maintain consistent locations

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1341]
**Is your feature request related to a problem? Please describe.**
CFE_MISSION_ES_CDS_MAX_FULL_NAME_LEN change could move `Table` location:
https://github.com/nasa/cFE/blob/e80aae94e0f56b868657daba965c590766a4dc57/modules/es/fsw/src/cfe_es_cds.h#L111

**Describe the solution you'd like**
Confirm CFE_ES_CDS_RegRec_t isn't "exposed" anywhere it matters, move `Name` to the end

**Describe alternatives you've considered**
If it is exposed, trade impacts and determine appropriate milestone

**Additional context**
Code review

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
After checking into this, I don't see this as a problem.  

There is an array of these registry records, so if the `CFE_MISSION_ES_CDS_MAX_FULL_NAME_LEN` size changes, every subsequent element in the array also changes location, thereby disrupting every field, not just the `Table` flag location.  

To avoid this the code does check the number of entries in the registry and will only attempt to re-use if the size matches, as well as flags at the beginning and end of the persistent memory space that will change locations if the overall registry array size changes.  So as a result the CDS will re-initialize itself if the size of this structure changed from what exists in persistent memory, either with respect to the number of registry entries, the size of the registry entry, or the size of the entire CDS pool.

The only weakness I can find is that it only checks the entire size of the overall pool.  So it is conceivable (although unlikely) that the both the size of the record changed well as the overall size of the pool, such that the size of the entire CDS remains the same.  That is, if the size of the  registry record increased but the size of the overall pool was decreased by the exact same amount, such that the trailer/end signature is at the exact same spot.  This is unlikely to happen by accident.
