### ISSUE TITLE
Replace multiline `CFE_ES_SYSLOG_APPEND` macro with inline function

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1349]
**Is your feature request related to a problem? Please describe.**
Use of multiline macros should be avoided (per coding standard):
https://github.com/nasa/cFE/blob/e80aae94e0f56b868657daba965c590766a4dc57/modules/es/fsw/src/cfe_es_log.h#L100-L106

**Describe the solution you'd like**
Replaced with inline, or one line macro/inline combo

**Describe alternatives you've considered**
Wrap with do {...} while(0), see https://gcc.gnu.org/onlinedocs/cpp/Swallowing-the-Semicolon.html

**Additional context**
Code review

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
Reviewing how CFE_ES_SYSLOG_APPEND is currently used, I'm having a hard time justifying why it even needs to exist at all anymore.  I think previously it was used in more places, perhaps, but now its down to just 4 instances in CDS code, and I can't see any reason why those 4 places can't just use `CFE_ES_WriteToSysLog` like everything else does.

It's an internal macro in `cfe_es_log.h` - not public - so my recommendation is to just remove it entirely.
