### ISSUE TITLE
Documentation builds should use separate directories

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#1378]
**Is your feature request related to a problem? Please describe.**
The 3 documentation targets (detaildesign, usersguide, osalguide) all share the same "doc" subdirectory for the doxygen run.  This can become a problem when trying to validate documentation builds and building with the `-j` option.  They work fine when built one at a time, but with `-j` at one point my machine got into an endless loop with two doxygen builds running in parallel that kept stepping on the other's files.

**Describe the solution you'd like**
Use separate dirs so that builds can be done in parallel without interfering with each other.

**Additional context**
This should also result in separate "warnings.log" files too, that can be more easily checked.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment]
Related to #389

**Comment by jphickey** [comment]
After nasa/osal#1033 and #1561 this fixes half of the issue - now just between the detail design and user guide sharing the same subdirectory and "warnings.log" file.
