### ISSUE TITLE
Consistent use of `CFE_EVS_EventType_Enum_t` (and clarify vs mask)

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1398]
**Is your feature request related to a problem? Please describe.**
Numerous locations where EventType is declared as uint16, but there's a defined type `CFE_EVS_EventType_Enum_t`

**Describe the solution you'd like**
Use CFE_EVS_EventType_Enum_t everywhere

**Describe alternatives you've considered**
Use uint16 everywhere

**Additional context**
Code review
#1447 - need to sort out enum vs mask use

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by skliper** [comment]
This allows the label to be printed for the value (naming convention), so it makes sense to have this for ENUM but not for general types.

**Comment by astrogeco** [comment]
[CCB:2021-04-21](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-April-21-2021) Discussed
