### ISSUE TITLE
Could not copy app.so to /cpu1/exe/cf/apps

### ISSUE THREAD

**Issue by aogrcs** [nasa/cFE#14]
Hi
When I delete all app.so in this fold, then I make clean, make config and make again, there are not any app.so in this fold? Is this right? Thanks!
Sincerely

**Comment by bethjt1220** [comment]
Are you using the cmake build system?  Try doing "make install" after doing "make".

**Comment by aogrcs** [comment]
Hi
If I did "make install" after "make", it said that:
make: *** No rule to make target 'install'.  Stop.

**Comment by aogrcs** [comment]
I edit the cfs.mak file and add .so for it, it worked now! Thanks
