### ISSUE TITLE
CFE_ES_RestoreFromCDS crashes when target block too small

### ISSUE THREAD

**Issue by zanzaben** [nasa/cFE#1413]
**Describe the bug**
If the pointer to the block of memory is smaller than CDS size then the app crashes 

**To Reproduce**
Call CFE_ES_RestoreFromCDS(void *RestoreToMemory, CFE_ES_CDSHandle_t Handle) with RestoreToMemory smaller than the size of Handle

**Expected behavior**
Should return an error code saying the target is too small. 

**Code snips**
Got this error from the console 

*** stack smashing detected ***: terminated
Aborted (core dumped)

**System observed on:**
Ubuntu 20.04

**Reporter Info**
Alex Campbell GSFC

**Comment by skliper** [comment]
Actually not a bug.  This is part of the API contract:
https://github.com/nasa/cFE/blob/e80aae94e0f56b868657daba965c590766a4dc57/modules/core_api/fsw/inc/cfe_es.h#L1133-L1139
