### ISSUE TITLE
Generate new set of CFE coverage test stubs

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#1417]
**Is your feature request related to a problem? Please describe.**
To achieve max flexibility the CFE coverage test stubs should have no built-in logic, with all handler logic in a separate function.

This is the pattern that was introduced with nasa/osal#966, along with the stub generator script.

**Describe the solution you'd like**
Run the stub generator script on CFE core API headers to generate a new set of "pure" stub implementation files with no extra logic in them.
Migrate any existing post-hook logic in the old stub to be a default handler function, as was done for OSAL stubs.

**Additional context**
Extension of original request in nasa/osal#832, but for CFE.  Depends on nasa/osal#966 to be accepted/merged before this can be done.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by jphickey** [comment]
Ping @asgibson for awareness, this will be the next step in getting all the stubs updated to work in the preferred manner.

**Comment by skliper** [comment]
Does this also fix #1393 and #1387?  If so, link.

**Comment by jphickey** [comment]
Yes this fixes #1387 but does not fix #1393.  I can do an add-on PR for that part though.

**Comment by asgibson** [comment]
I have pulled this update and run with cFS https://github.com/nasa/cFE/commit/c8b5e00bb722d8f59787ae8f82634feba5d39f60 with the only change being the use of cFE https://github.com/nasa/cFE/pull/1463.  All the CF unit tests run as they did before with no discernible difference.  As this is the goal, that is success.

One note: None of the new "handler" override of any cFE stub was attempted.  This only shows that whatever cFE API methods that are called by CF unit tests still operate as expected.  This is not extensive, but several are called during testing.

Some of those used (not a complete list):

- CFE_EVS_SendEvent
- CFE_TBL_ReleaseAddress
- CFE_TBL_GetAddress
- CFE_MSG_GetFcnCode
- CFE_MSG_GetSize
- CFE_MSG_SetMsgTime
- CFE_TIME_GetTime
- CFE_SB_TransmitMsg
