### ISSUE TITLE
Include element that caused write error in event reporting in `CFE_EVS_WriteAppDataFileCmd`

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1432]
**Is your feature request related to a problem? Please describe.**
Element that caused error not included in event, so not obvious how much of the write was completed
https://github.com/nasa/cFE/blob/73c338d544f85cb0c1a97b743d3ae9f7a35039b5/modules/evs/fsw/src/cfe_evs_task.c#L1746-L1748

**Describe the solution you'd like**
Add the element number

**Describe alternatives you've considered**
None

**Additional context**
Code review

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by thnkslprpt** [comment]
@skliper Were you thinking something like this?
![image](https://user-images.githubusercontent.com/9024662/235798547-44acfd30-2428-4634-9fd2-bb38972a77d5.png)
or
![image](https://user-images.githubusercontent.com/9024662/235798626-24a9b517-bb6b-46c2-81fb-63a12787ba1f.png)

**Comment by thnkslprpt** [comment]
@skliper - how would you get the second value (of)?

Isn't the total number of entries that was supposed to be written only known after the `for` loop ends? Or do you mean to just use `CFE_PLATFORM_ES_MAX_APPLICATIONS`?
