### ISSUE TITLE
Remove defines for EVS LogMode

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1446]
**Is your feature request related to a problem? Please describe.**
Enum is defined here:
https://github.com/nasa/cFE/blob/c8b5e00bb722d8f59787ae8f82634feba5d39f60/modules/core_api/fsw/inc/cfe_evs_extern_typedefs.h#L66-L81

Defines here:
https://github.com/nasa/cFE/blob/c8b5e00bb722d8f59787ae8f82634feba5d39f60/modules/evs/fsw/inc/cfe_evs_msg.h#L910-L912

**Describe the solution you'd like**
Remove defines, replace any references with the enums.

**Describe alternatives you've considered**
Boolean for overwrite (although cmd/tlm should be fixed size)

**Additional context**
Code review

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by skliper** [comment]
Ping @pepepr08

**Comment by pepepr08** [comment]
I'll work on this
