### ISSUE TITLE
Combine mostly duplicated logic in `CFE_SB_BroadcastBufferToRoute`

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1460]
**Is your feature request related to a problem? Please describe.**
Duplicated logic:
https://github.com/nasa/cFE/blob/c8b5e00bb722d8f59787ae8f82634feba5d39f60/modules/sb/fsw/src/cfe_sb_api.c#L1650-L1667

**Describe the solution you'd like**
Factor out, make an else with shared logic and internal if for the unique logic

**Describe alternatives you've considered**
None

**Additional context**
Code review

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by thnkslprpt** [comment]
You're thinking something like this Jake (@skliper)?
https://github.com/nasa/cFE/blob/3d8829ecb98343552c2bb66cf1d45e9b83420930/modules/sb/fsw/src/cfe_sb_api.c#L1661-L1678

**Comment by thnkslprpt** [comment]
Cheers Jake.
