### ISSUE TITLE
Add ${ARGN} to add_cfe_coverage_test in arch_build.cmake

### ISSUE THREAD

**Issue by asgibson** [nasa/cFE#1490]
**Is your feature request related to a problem? Please describe.**
Trying to build CF unit tests with additional libraries through add_cfe_coverage_test does not work because ARGN is not added in the target_link_libraries call.  

**Describe the solution you'd like**
Add `${ARGN}` into target_link_libraries call in add_cfe_coverage_test so that additional libraries can be given where necessary.

**Describe alternatives you've considered**
Writing my own coverage test addition for my use case, but just adding the ${ARGN} in add_cfe_coverage_test works, so why re-invent?

**Additional context**
The addition should be transparent to any other calls currently in use; it is opt in only.  ARGN should be empty in current use cases (it could not be, but that is unlikely).

**Requester Info**
Alan Gibson  NASA/GSFC 587

**Comment by jphickey** [comment]
The ${ARGN} convention is that it is basically an extension of the last argument - that is, a variably-sized list of extra arguments that are the same type/intent as the last argument.    In this context, it means that it would be specifying multiple _source files_ for the test (aka the existing `UT_SRCS` arg).

I think it was just an oversight/mistake that `${ARGN}` was not included in the add_library.  This can be fixed.

However, that being said, its is for source files, not libraries.  

Suggestion is to use `add_cfe_coverage_dependency` if you need to add extra link libraries.
