### ISSUE TITLE
Declare leap seconds as unsigned

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1533]
**Is your feature request related to a problem? Please describe.**
`int16` type used for `LeapSeconds` in command payload:
https://github.com/nasa/cFE/blob/84ba9a9974794e239b989cdc4e2359216e44fab0/modules/time/fsw/inc/cfe_time_msg.h#L749-L752

also in HK:
https://github.com/nasa/cFE/blob/84ba9a9974794e239b989cdc4e2359216e44fab0/modules/time/fsw/inc/cfe_time_msg.h#L922-L926

API's:
https://github.com/nasa/cFE/blob/84ba9a9974794e239b989cdc4e2359216e44fab0/modules/time/fsw/src/cfe_time_api.c#L298

**Describe the solution you'd like**
Convert to `uint16`.

**Describe alternatives you've considered**
None

**Additional context**
Code review

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by zanzaben** [comment]
Leap Seconds can technically be negative. So far everyone in history has been to add a second so it is incredibly unlikely that they will overall be negative but not impossible.

**Comment by astrogeco** [comment]
I vote we keep the signed int: 

> [...] if the Earth's rotation keeps accelerating, as it has done in 2020, the IERS may decide to announce the world's first negative leap second at some point in the future.

https://www.timeanddate.com/time/leapseconds.html

**Comment by skliper** [comment]
Concur, closed as invalid.
