### ISSUE TITLE
CFE_ES_GetPoolBufInfo Header has incorrect return description

### ISSUE THREAD

**Issue by zanzaben** [nasa/cFE#1606]
**Describe the bug**
The return in the header says it returns Execution status but it actually returns the buffer size or error code. 

**Expected behavior**
Header file should be changed to match the implementation. 

**Additional context**
The code that does this has a comment saying it's not workable so we could also change the implementation 

https://github.com/nasa/cFE/blob/176e3df03f54f7753cb34beb3e986202604d6cef/modules/es/fsw/src/cfe_es_mempool.c#L541-L550

**Reporter Info**
Alex Campbell GSFC

**Comment by jphickey** [comment]
Yeah, it would be nice to fix this implementation, but that is an API change.  Internally, the code should support any block size up to `size_t` , but with a historical `int32` return type that returns the size this is limited to 2GB in practice.  Which is still beyond what is typically needed - in our test configurations it only goes up to 80k bytes - so 2GB is still far above what is typically used here.

Ideally we should note in the user guide and/or release notes that pools (currently) should not exceed 2GB in size.  Maybe in a future cFE we can fix the rest of the APIs.   But most flight hardware doesn't even have 2GB of RAM total, so I doubt any users will have an issue with that.
