### ISSUE TITLE
Fix documentation workflow warning.log archive

### ISSUE THREAD

**Issue by astrogeco** [nasa/cFE#1629]
**Describe the bug**
The documentation CI workflow has a typo in the directory for the usersguide-warnings.log output file. 

**To Reproduce**
See <https://github.com/nasa/cFE/runs/2847522531?check_suite_focus=true>

**Expected behavior**
Workflow runs successfully and reports and archives warnings

**Code snips**
https://github.com/nasa/cFE/blob/d03e24e675fcd253222e40a5c544920e03854c5f/.github/workflows/build-documentation.yml#L116

**Additional context**
This popped up after the update to the documentation build and I missed it when fixing up the IC

**Comment by jphickey** [comment]
Just ran into this on my PR, seems like a concurrent add/update issue (this is a new-ish workflow item, right?)
