### ISSUE TITLE
Add functional tests for cFE Message header APIs

### ISSUE THREAD

**Issue by zanzaben** [nasa/cFE#1677]
**Is your feature request related to a problem? Please describe.**
Need open source functional tests for certifiability

**Describe the solution you'd like**
Add functional tests for cFE Message header APIs
    CFE_MSG_Init - Initialize a message.
    CFE_MSG_GetSize - Gets the total size of a message.
    CFE_MSG_SetSize - Sets the total size of a message.
    CFE_MSG_GetType - Gets the message type.
    CFE_MSG_SetType - Sets the message type.
    CFE_MSG_GetHeaderVersion - Gets the message header version.
    CFE_MSG_SetHeaderVersion - Sets the message header version.
    CFE_MSG_GetHasSecondaryHeader - Gets the message secondary header boolean.
    CFE_MSG_SetHasSecondaryHeader - Sets the message secondary header boolean.
    CFE_MSG_GetApId - Gets the message application ID.
    CFE_MSG_SetApId - Sets the message application ID.
    CFE_MSG_GetSegmentationFlag - Gets the message segmentation flag.
    CFE_MSG_SetSegmentationFlag - Sets the message segmentation flag.
    CFE_MSG_GetSequenceCount - Gets the message sequence count.
    CFE_MSG_SetSequenceCount - Sets the message sequence count.
    CFE_MSG_GetNextSequenceCount - Gets the next sequence count value (rolls over if appropriate)
    CFE_MSG_GetEDSVersion - Gets the message EDS version.
    CFE_MSG_SetEDSVersion - Sets the message EDS version.
    CFE_MSG_GetEndian - Gets the message endian.
    CFE_MSG_SetEndian - Sets the message endian.
    CFE_MSG_GetPlaybackFlag - Gets the message playback flag.
    CFE_MSG_SetPlaybackFlag - Sets the message playback flag.
    CFE_MSG_GetSubsystem - Gets the message subsystem.
    CFE_MSG_SetSubsystem - Sets the message subsystem.
    CFE_MSG_GetSystem - Gets the message system.
    CFE_MSG_SetSystem - Sets the message system.
    CFE_MSG_GenerateChecksum - Calculates and sets the checksum of a message.
    CFE_MSG_ValidateChecksum - Validates the checksum of a message.
    CFE_MSG_SetFcnCode - Sets the function code field in a message.
    CFE_MSG_GetFcnCode - Gets the function code field from a message.
    CFE_MSG_GetMsgTime - Gets the time field from a message.
    CFE_MSG_SetMsgTime - Sets the time field in a message.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requester Info**
Alex Campbell GSFC

**Comment by skliper** [comment]
Note these APIs are fully exercised via the coverage tests (there's no lower level calls that require stubs), so this is not a priority for Caelum.
