### ISSUE TITLE
Add functional tests for cFE Message Id APIs

### ISSUE THREAD

**Issue by zanzaben** [nasa/cFE#1678]
**Is your feature request related to a problem? Please describe.**
Need open source functional tests for certifiability

**Describe the solution you'd like**
Add functional tests for cFE Message Id APIs
    CFE_MSG_GetMsgId - Gets the message id from a message.
    CFE_MSG_SetMsgId - Sets the message id bits in a message.
    CFE_MSG_GetTypeFromMsgId - Gets message type using message ID.
	
**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requester Info**
Alex Campbell GSFC

**Comment by skliper** [comment]
Low priority for Caelum, coverage test completely exercises these.
