### ISSUE TITLE
Add functional tests for cFE Table Registration APIs

### ISSUE THREAD

**Issue by zanzaben** [nasa/cFE#1685]
**Is your feature request related to a problem? Please describe.**
Need open source functional tests for certifiability

**Describe the solution you'd like**
Add functional tests for cFE Table Registration APIs
    CFE_TBL_Register - Register a table with cFE to obtain Table Management Services.
    CFE_TBL_Share - Obtain handle of table registered by another application.
    CFE_TBL_Unregister - Unregister a table.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requester Info**
Alex Campbell GSFC

**Comment by nmullane** [comment]
I'll start working on this.
