### ISSUE TITLE
Add functional tests for cFE Access Table Content APIs

### ISSUE THREAD

**Issue by zanzaben** [nasa/cFE#1687]
**Is your feature request related to a problem? Please describe.**
Need open source functional tests for certifiability

**Describe the solution you'd like**
Add functional tests for cFE Access Table Content APIs
    CFE_TBL_GetAddress - Obtain the current address of the contents of the specified table.
    CFE_TBL_GetAddresses - Obtain the current addresses of an array of specified tables.
    CFE_TBL_ReleaseAddress - Release previously obtained pointer to the contents of the specified table.
    CFE_TBL_ReleaseAddresses - Release the addresses of an array of specified tables.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requester Info**
Alex Campbell GSFC

**Comment by nmullane** [comment]
I'll start working on this.
