### ISSUE TITLE
Add functional tests for cFE Time Arithmetic APIs

### ISSUE THREAD

**Issue by zanzaben** [nasa/cFE#1689]
**Is your feature request related to a problem? Please describe.**
Need open source functional tests for certifiability

**Describe the solution you'd like**
Add functional tests for cFE Time Arithmetic APIs
    CFE_TIME_Add - Adds two time values.
    CFE_TIME_Subtract - Subtracts two time values.
    CFE_TIME_Compare - Compares two time values.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requester Info**
Alex Campbell GSFC

**Comment by nmullane** [comment]
I'll start working on this.
