### ISSUE TITLE
Remove application/child task registration API requirements

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1709]
**Is your feature request related to a problem? Please describe.**
APIs were removed in #1250, registration handled by ES and no longer requires API.

cES1300 and 

**Describe the solution you'd like**
Remove associated requirements, cES1300 - ES: Register Application and cES1313 - ES: Register Child Task

**Describe alternatives you've considered**
None

**Additional context**
#1250, #1215

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
Closed by #1701 and #1720
