### ISSUE TITLE
Remove requirements for message initialization "clear" vs "no-clear" options

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1713]
**Is your feature request related to a problem? Please describe.**
CFE_MSG_Init no longer supports "clear" vs "no-clear" options due to abstraction incompatibilities.
cSB4315.1 - SB: Initialize Message - Clear
cSB4315.2 - SB: Initialize Message - No Clear

**Describe the solution you'd like**
Remove these "special option" requirements.  The requirement is that it initializes the packet (cSB4315), the design/implementation describes the exact behavior (there are many possible compliant implementations by design).  Ambiguous options that can not be abstracted should be avoided in the API.

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
Closed by #1701 and #1720
