### ISSUE TITLE
Remove get message checksum requirement

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1714]
**Is your feature request related to a problem? Please describe.**
As part of the message module refactor the CFE_SB_GetChecksum external API was determined to have no use case.

**Describe the solution you'd like**
Remove associated requirement:
cSB4326 - SB: Get Checksum

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
Closed by #1701 and #1720
