### ISSUE TITLE
Requirements scrub for Caelum development cycle

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1717]
**Is your feature request related to a problem? Please describe.**
Caelum development included API additions, need updated requirements.

**Describe the solution you'd like**
Update:
ES: Report Task and Application Name,cES1305 -> ES: Get Task Information

New:
ES: Get Library Information,cES1344
ES: Delete Memory Pool,cES1345
ES: Get Generic Counter Name,cES1346
FS: Filename Auto-Complete,cES1605
FS: Background File Dump,cES1606
SB: Delete Pipe,cSB4302
SB: Set Packet Type,cSB4346
SB: Get Header Field,cSB4347
SB: Set Header Field,cSB4348
SB: Get Sequence Count,cSB4349
SB: Set Sequence Count,cSB4350
SB: Get Next Sequence Count,cSB4351
SB: Get Type From MsgId,cSB4352

**Describe alternatives you've considered**
None

**Additional context**
Note - resource ID APIs and *_ToIndex APIs were categorized as "Design" so they aren't associated directly with requirements (a different implementation may not require these).  Of similar note, the message implementation supports user defined header fields, so the requirement is generic where there isn't internal dependencies on the field.

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
Closed by #1701 and #1720
