### ISSUE TITLE
Remove SB: Last Message Sender Info, cSB4309 requirement (removed API)

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1741]
**Is your feature request related to a problem? Please describe.**
Support for getting the last message sender was removed in the Caelum development cycle, need to remove the requirement

**Describe the solution you'd like**
Remove cSB4309 - SB: Last Message Sender Info requirement

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
Adding historical Issues for context 

https://github.com/nasa/cFE/issues/127 

we might want to revisit this some form of this requirement from a security perspective in the future
