### ISSUE TITLE
Improve consistency when working with OSAL status codes

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#1755]
**Is your feature request related to a problem? Please describe.**
Quite often in the CFE implementation, OSAL status codes are mixed with CFE status codes, often times sharing a single stack variable to hold either one, and even switching back and forth.

To improve clarity and consistency, OSAL status codes should be stored in a _separate_ stack variable from the CFE status codes.  Ideally, in the future, these should also migrate to a separate type (e.g. `osal_status_t`, as in nasa/osal#1108, or `CFE_Status_t`, as in nasa/cfe#921).  

**Describe the solution you'd like**
- Anywhere that an OSAL status code is stored on the stack, make a _separate_ variable.
- Always use a consistent name for that variable, e.g. `OsStatus`  (as opposed to "Status" or "ReturnCode" etc, which are vague).
- Avoid intermixing CFE status codes and OSAL status codes whenever possible (there will still be some times its necessary, when calling generic functions).  When it is necessary, make conversions between these types explicit/obvious via comments and/or type casting.
- When printing OSAL status codes in a log or event message, print it as long decimal (%ld), not as hex as the CFE status codes are.  This is because OSAL defines its status codes as decimal numbers, so logs/events should match this.

**Additional context**
This can be considered a prerequisite to nasa/cfe#921 (cannot introduce a unique `CFE_Status_t` type until it is no longer being used to store OSAL codes).

This would be a fix for next release (not 7.0.0).

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by zanzaben** [comment]
This is yet another addition to the growing list of problems due to OSAL error codes. #1676 #1672 #1723 #1675 #1599.

**Comment by jphickey** [comment]
> This is yet another addition to the growing list of problems due to OSAL error codes. #1676 #1672 #1723 #1675 #1599.

Yes, I consider this related to #1676, as this addresses part of that one - however that previous issue was more general in nature.  This issue just deals with specifically having a separate variable for OSAL status vs. CFE status.
