### ISSUE TITLE
Write Resource ID functional test to check maximum

### ISSUE THREAD

**Issue by astrogeco** [nasa/cFE#1760]
**Is your feature request related to a problem? Please describe.**
Need open source functional tests for certifiability

**Describe the solution you'd like**
Add additional checks to functional tests for ES Resource ID to Index that ensure the returned index is less than the maximum allowed for that resource type

**Describe alternatives you've considered**
None

**Requester Info**
_Originally posted by @astrogeco in https://github.com/nasa/cFE/pull/1734#issuecomment-892799313_

**Comment by nmullane** [comment]
I'll work on this.

**Comment by nmullane** [comment]
I can't edit the issue text, so should I create a new issue with a fleshed out description? Or the following can just be copied into this issue's description

---


**Is your feature request related to a problem? Please describe.**
Need open source functional tests for certifiability

**Describe the solution you'd like**
Add additional checks to functional tests for ES Resource ID to Index that ensure the returned index is less than the maximum allowed for that resource type

**Describe alternatives you've considered**
None

**Requester Info**
Niall Mullane - GSFC 582 Intern

**Comment by jphickey** [comment]
I was able to update the description text.  I'll watch for the PR and review.  Thanks!
