### ISSUE TITLE
Delete/exit/create child task additional error codes need to be documented in API and tested (related to requirements)

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1769]
**Is your feature request related to a problem? Please describe.**
We've got requirements to error if `CFE_ES_DeleteChildTask` or `CFE_ES_ExitChildTask` relate to the main app task:
https://github.com/nasa/cFE/blob/c4ae5b262727f4f1381df596d00a6acc11c3a62c/docs/cFE_FunctionalRequirements.csv#L114
https://github.com/nasa/cFE/blob/c4ae5b262727f4f1381df596d00a6acc11c3a62c/docs/cFE_FunctionalRequirements.csv#L116

Also `CFE_ES_CreateChildTask` can not be called from a child task:
https://github.com/nasa/cFE/blob/c4ae5b262727f4f1381df596d00a6acc11c3a62c/docs/cFE_FunctionalRequirements.csv#L112

**Describe the solution you'd like**
Document in the API and exercise these cases and test for return codes:
`CFE_ES_ERR_CHILD_TASK_DELETE_MAIN_TASK`
`CFE_ES_ERR_CHILD_TASK_CREATE`
Note `CFE_ES_ExitChildTask` is a void so no error code to check but shouldn't exit from a main app, exercise from main test app task to confirm

**Describe alternatives you've considered**
None

**Additional context**
Hopefully this would be caught by the upcoming API scrub (@jphickey), but documenting explicitly since it's a requirement verification issue.  Not sure if it's easier to fix now or with the rest of the updates... open to whatever is easiest.

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
Note - as part of previous PR #1869 this adds test cases that cover the following cases of CFE_ES_ERR_CHILD_TASK_DELETE_MAIN_TASK and CFE_ES_ERR_CHILD_TASK_CREATE status codes from the respective APIs (prevents creating child from child, or deleting main task from child, etc).

The remaining work item is to invoke CFE_ES_ExitChildTask
