### ISSUE TITLE
Replace cFE_FTAssert_VOIDCALL with new UtAssert_VOIDCALL

### ISSUE THREAD

**Issue by astrogeco** [nasa/cFE#1774]
**Is your feature request related to a problem? Please describe.**

The cFE Functional Test use a macro called `cFE_FTAssert_VOIDCALL`. That macro should be deleted and all existing references to it replaced with `UtAssert_VOIDCALL`.

**Describe the solution you'd like**

Replace old macro.

**Describe alternatives you've considered**
Leave as is.

**Additional context**
See https://github.com/nasa/cFE/issues/1744#issuecomment-895286108

**Comment by zanzaben** [comment]
The cFE Functional Test use a macro called cFE_FTAssert_VOIDCALL. That macro should be deleted and all existing references to it replaced with UtAssert_VOIDCALL.

**Comment by jphickey** [comment]
In addition to this one I'd also like to replace these three as well (see #1790)

- `cFE_FTAssert_ResourceID_EQ` -> `CFE_UtAssert_RESOURCEID_EQ`
- `cFE_FTAssert_ResourceID_Undefined` -> `CFE_UtAssert_RESOURCEID_UNDEFINED`
- `cFE_FTAssert_NOT_CFE_SUCCESS` -> `CFE_UtAssert_NOT_SUCCESS`

Side note - We really shouldn't have generic macros in `cfe_testcase` app, this may not be the only "test" app that exists (users can add additional test apps for their apps/functions).  So CFE-specific assert macros should really be defined in the `cfe_assert` library, such that they can be used by user-defined test apps as well.
