### ISSUE TITLE
No Success Test and Boundaries for CFE_TBL_ReleaseAddresses

### ISSUE THREAD

**Issue by ArielSAdamsNASA** [nasa/cFE#1791]
**Is your feature request related to a problem? Please describe.**
From #548. No Success Test for CFE_TBL_ReleaseAddresses. No test on boundary conditions for NumTables.

**Describe the solution you'd like**
Add a success test for CFE_TBL_ReleaseAddresses in cFE/modules/tbl/ut-coverage/tbl_UT.c. Test boundary conditions for NumTables. 

**Requester Info**
Ariel Adams, ASRC Federal

**Comment by nmullane** [comment]
I'll work on this.
