### ISSUE TITLE
SB coverage test - need to verify MsgSendErrorCounter increments when msg too big

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1827]
**Is your feature request related to a problem? Please describe.**
Missing verification of MsgSendErrorCounter increment on message too big (requirement)

**Describe the solution you'd like**
Add verification

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
I wanted to do this, but we do not expose the counter other than in the housekeeping telemetry stream.  So without subscribing to the TLM packet somehow, we can't read the counter (unless there was something I missed?).  I assume a CMD/TLM-based test could do this more easily.

**Comment by jphickey** [comment]
I suppose the test could subscribe to the SB HK TLM message, but then you'd have a dependency on SCH running, unless we also generated the SEND_HK command locally too?
