### ISSUE TITLE
EVS Unit Test Code Coverage Incomplete in Task.c (GSFC DCR 8492)

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#189]
cfe_evs_task.c - 99.61% % coverage (2 Lines of Code NOT executed)

The lines not covered are in CFE_EVS_TaskInit:

        -:  385:   /* Register EVS task for event services */
        5:  386:   Status = CFE_EVS_Register(NULL, 0, CFE_EVS_BINARY_FILTER);
        5:  387:   if (Status != CFE_SUCCESS)
        -:  388:   {
    #####:  389:      CFE_ES_WriteToSysLog("EVS:Call to CFE_EVS_Register Failed:RC=0x%08X\n",(unsigned int)Status);
    #####:  390:      return Status;
        -:  391:   }

REASON: None

**Comment by skliper** [comment]
_Imported from trac issue 158.  Created by sstrege on 2016-05-09T20:05:14, last modified: 2019-03-01T15:27:58_

**Comment by skliper** [comment]
_Trac comment by glimes on 2016-10-18 15:07:03:_

Remove my name from many tickets (where it was applied by default), so others can tell that there are tickets that need some attention.

**Comment by avan989** [comment]
I can do this.

**Comment by skliper** [comment]
Excellent, I suggest start by rerunning the test to identify any currently missing coverage.
