### ISSUE TITLE
Comment about MISSION_GLOBAL_APPLIST is confusing

### ISSUE THREAD

**Issue by asgibson** [nasa/cFE#1918]
**Describe the bug**
The first sentence for the description of MISSION_GLOBAL_APPLIST in `cFE/cmake/sample_defs/targets.cmake` does not make sense. 'The "MISSION_GLOBAL_APPLIST" is a set of apps/libs that will be built for every defined and target.'  Specifically 'defined and target' does not provide clarity as to the intent here.  Removing the 'and' would have it make sense, but was something else meant to be imparted here?

**To Reproduce**
N/A

**Expected behavior**
N/A

**Code snips**
https://github.com/nasa/cFE/blob/5e41330979586bcdb113f491ea6c38ff9975fc72/cmake/sample_defs/targets.cmake#L84-L85

**System observed on:**
N/A

**Additional context**
N/A

**Reporter Info**
Alan Gibson
NASA GSFC/587

**Comment by jphickey** [comment]
Thanks for catching.  Confirmed - just need to remove the word "and" here.
