### ISSUE TITLE
ES missing branch in CFE_ES_RegisterCDSEx, overwrite success check doesn't make sense

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1929]
**Is your feature request related to a problem? Please describe.**
I suspect there were code changes that made the check redundant/pointless since RegUpdateStatus only gets set if Status == CFE_SUCCESS before this point, so there's no way for it to not be success and for Status to also not be success.
```
     443         [ +  + ]:         14 :     if (RegUpdateStatus != CFE_SUCCESS)
     444                 :            :     {
     445                 :          2 :         CFE_ES_WriteToSysLog("%s: Failed to update CDS Registry (Stat=0x%08X)\n", __func__,
     446                 :            :                              (unsigned int)RegUpdateStatus);
     447                 :            : 
     448                 :            :         /*
     449                 :            :          * Return failure only if this was the primary error,
     450                 :            :          * do not overwrite a preexisting error.
     451                 :            :          */
     452         [ +  - ]:          2 :         if (Status == CFE_SUCCESS)
     453                 :            :         {
     454                 :          2 :             Status = RegUpdateStatus;
     455                 :            :         }
     456                 :            :     }
```
here:
https://github.com/nasa/cFE/blob/e5d4ed9a26ce3c991796494bc546341d5036b970/modules/es/fsw/src/cfe_es_cds.c#L443-L456

**Describe the solution you'd like**
Really collapses back down into just one status... no point for two.

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by thnkslprpt** [comment]
> I suspect there were code changes that made the check redundant...

@skliper
- You're right, [here](https://github.com/nasa/cFE/pull/946/files#r1186575348) in https://github.com/nasa/cFE/pull/946
