### ISSUE TITLE
ES branch missing coverage in CFE_ES_GenPoolRecyclePoolBlock and CFE_ESGenPoolCreatePoolBlock, NULL pointer check

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1930]
**Is your feature request related to a problem? Please describe.**
The NULL pointer check in CFE_ES_GenPoolRecyclePoolBlock would require either exposing this internal routine or getting really lucky corrupting the record from a separate task since it's valid from the calling function.
```
     119                 :         37 :     BucketPtr = CFE_ES_GenPoolGetBucketState(PoolRecPtr, BucketId);
     120 [ +  - ][ +  + ]:         37 :     if (BucketPtr == NULL || BucketPtr->RecycleCount == BucketPtr->ReleaseCount || BucketPtr->FirstOffset == 0)
                 [ +  + ]
```
here:
https://github.com/nasa/cFE/blob/e5d4ed9a26ce3c991796494bc546341d5036b970/modules/es/fsw/src/cfe_es_generic_pool.c#L119-L120

Same pattern in CFE_ES_GenPoolCreatePoolBlock:
```
     180                 :         31 :     BucketPtr = CFE_ES_GenPoolGetBucketState(PoolRecPtr, BucketId);
     181         [ -  + ]:         31 :     if (BucketPtr == NULL)
     182                 :            :     {
     183                 :            :         /* no buffers in pool to create */
     184                 :          0 :         return CFE_ES_BUFFER_NOT_IN_POOL;
     185                 :            :     }
```
here
https://github.com/nasa/cFE/blob/e5d4ed9a26ce3c991796494bc546341d5036b970/modules/es/fsw/src/cfe_es_generic_pool.c#L180-L185

**Describe the solution you'd like**
Questionable usefulness, since it can likely only be hit if a pool without a mutex is shared between tasks and access is not serialized (BAD!).  If the check does remain, could just expose the internal function to force the failure.

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by avan989** [comment]
I'll work on this.
