### ISSUE TITLE
Suggestion: Modular platform and app makefiles

### ISSUE THREAD

**Issue by EzraBrooks** [nasa/cFE#2]
One major improvement that could be made to cFE is the ability to specify which apps to build and which platforms to build for at runtime, instead of by changing the Makefiles. CACTUS has a rudimentary implementation of this (see https://github.com/CACTUS-Mission/cFE/commit/bec0b577f2d0f788c17fe212d6a78b2c4cad3f5e) so that we can declare `THE_APPS` as an environment variable. I think it would be a huge improvement to the build process to be able to optionally declare THE_APPS, PSP, BSP, and more at the make command line, i.e.
```bash
make THE_APPS="sample_lib sample_app"
```
Some tricks may need to be done to allow this to propagate to make sub-tasks, as those variables would only be accessible in the Makefile in the directory the command is run.

**Comment by the-other-james** [comment]
There is better support for this in cFS 6.6 which uses cmake and can define target specific apps. 6.6 should be available for public release soon.
