### ISSUE TITLE
Username change

### ISSUE THREAD

**Issue by paulober** [nasa/cFE#2021]
I changed my username from (at)pavll to @paulober. The problem is that someone else claimed my old name an now he's mentioned every time (at)pavll was used(mostly PRs). Do I have to state this change somewhere for my nasa opensource contribs(because GitHub doesn't redirect @ mentions to new usernames)?

**Comment by astrogeco** [comment]
Thanks for letting us know! Hopefully your old commit history still shows up under your user account!

**Comment by paulober** [comment]
Thanks for understanding and changing my @mentions in your PRs. I think so...
