### ISSUE TITLE
Message struct definitions in default_cfe_msg_hdr_priext.h conflict with cfe_msg_api_typedefs.h

### ISSUE THREAD

**Issue by plexilcrf** [nasa/cFE#2053]
**Describe the bug**
When MISSION_INCLUDE_CCSDSEXT_HEADER is set to TRUE in global_build_options.cmake, the file modules/msg/option_inc/default_cfe_msg_hdr_priext.h is included in place of .../default_cfe_msg_hdr_pri.h. The definitions in default_cfe_msg_hdr_priext.h conflict with those in modules/core_api_fsw/inc/cfe_msg_api_typedefs.h.

**To Reproduce**

1. Define a mission configuration. Modify global_build_options.cmake by adding the following two lines:
    set(MISSION_INCLUDE_CCSDSEXT_HEADER TRUE)
    set(MISSION_MSGID_V2 TRUE)

2. Attempt to build cFS. Observe compilation errors while compiling. See attached file cfe_typedef_errors.txt for example error messages.

[cfe_typedef_errors.txt](https://github.com/nasa/cFE/files/8119528/cfe_typedef_errors.txt)

**Expected behavior**
cFE should compile cleanly.

**Code snips**
See attached patch file. 

[cFE_msgdefs_patch_2022-02-22.txt](https://github.com/nasa/cFE/files/8119526/cFE_msgdefs_patch_2022-02-22.txt)

**System observed on:**
 - Hardware: VirtualBox emulation of an x86-64 system on macOS 11.6.3
 - OS: Ubuntu Linux 20.04
 - Compiler: GCC v9.3.0 with -m32 flag, all other options standard for RelWithDebInfo build type
 - Versions: cFE tag v7.0.0-rc4; OSAL tag v6.0.0-rc4; PSP tag v1.6.0-rc4

**Additional context**

**Reporter Info**
Chuck Fry, QTS Inc., a subcontractor to KBR Wyle on the ISRDS3 contract at NASA ARC Code TI
chuck.fry@nasa.gov

**Comment by skliper** [comment]
Fixed in https://github.com/nasa/cFE/pull/1983
