### ISSUE TITLE
Update RTEMS toolchain files for RTEMS 4.11, 5, and 6

### ISSUE THREAD

**Issue by acudmore** [nasa/cFE#2096]
**Is your feature request related to a problem? Please describe.**
This is part of the RTEMS updates described here: https://github.com/nasa/cFS/discussions/468
The RTEMS toolchain files require a few minor changes in order to:

- Add compatibility for RTEMS 6
- Allow both static and dynamically linked cFE core implementations
- Allow the Gaisler RCC toolchain to be used

**Describe the solution you'd like**
I would like do the following to existing RTEMS toolchain files:

- Add a define to indicate that the cFE core is dynamically linked
- Add a define to indicate the version of RTEMS being used. This is a new define, and when the proper OSAL and PSP changes have been made, the old defines will be removed. The new define has the form -DOS_RTEMS_X where the old define has the form -D_RTEMS_X_
- Add a RTEMS_BSP_SPECS variable to allow a version specific specs option to be specified. This allows the same CMake platform file for RTEMS to be used for RTEMS 4, 5, and 6.

I would also like to add a new toolchain file for i686-rtems6

**Describe alternatives you've considered**
The alternative is to create two additional Cmake platform files in the PSP for RTEMS 6 and Gaisler RCC 5. This is not ideal because there would be 3 separate RTEMS Cmake platform files to maintain and they would be almost the same.

**Additional context**
The toolchain file changes are the only changes needed in the cFE to support RTEMS 4.11, 5, and 6 as well as Gaisler RTEMS 5 (RCC 1.3.x). These changes also will enable a new generic-rtems OSAL BSP and PSP to be added later.

**Requester Info**
Alan Cudmore, NASA/GSFC Code 582.0

**Comment by astrogeco** [comment]
[CCB:2022.04.27](https://github.com/nasa/cFS/wiki/CCB:-2022.04.27) Discussed
