### ISSUE TITLE
URL to "cFE Users Guide" in the top-level README.md returns a 404

### ISSUE THREAD

**Issue by acarrillo** [nasa/cFE#2104]
**Describe the bug**
This is the URL to the `cFE_Users_Guide.pdf` given on the front page README.md: https://github.com/nasa/cFS/blob/gh-pages/cFE_Users_Guide.pdf

The URL returns a 404.

**To Reproduce**
1. Go to https://github.com/nasa/cFE/blob/main/README.md
2. Follow the link given by:
> The detailed cFE user's guide can be viewed at https://github.com/nasa/cFS/blob/gh-pages/cFE_Users_Guide.pdf.

3. Click the link and see the 404.

**Expected behavior**
The document should exist at the given URL.

**Reporter Info**
Alex Carrillo

**Comment by skliper** [comment]
Correct link is now https://github.com/nasa/cFE/blob/gh-pages/cfe-usersguide.pdf

**Comment by acarrillo** [comment]
Thank you @skliper !
