### ISSUE TITLE
Update wrong comment regarding the value of CFE_SB_INVALID_MSG_ID 

### ISSUE THREAD

**Issue by pepepr08** [nasa/cFE#2116]
**Describe the bug**
CFE_SB_INVALID_MSG_ID value is no longer the maximum representable number of type CFE_SB_MsgId_t. Comment needs to be updated.

**Code snips**
[Link to lines of code](https://github.com/nasa/cFE/blob/main/cmake/sample_defs/cpu1_platform_cfg.h#L167-L168)

**Reporter Info**
Jose F. Martinez Pedraza / GSFC 582

**Comment by pepepr08** [comment]
Re-oppening since issue is only partially solved. When I created the issue, I could have been more specific about the places where it needed to be fixed. The comment was fixed in default_cfe_sb_internal_cfg.h, but it also needs to be fixed in example_platform_config.h It still says `CFE_PLATFORM_SB_HIGHEST_VALID_MSGID lower limit is 1, up to CFE_SB_INVALID_MSG_ID - 1.` and `CFE_SB_INVALID_MSG_ID` seems to be set to 0.  https://github.com/nasa/cFE/blob/d0e9564b09ead61c60a8af235431a69b9aef85c0/cmake/sample_defs/example_platform_cfg.h#L1149C10-L1149C96

**Comment by thnkslprpt** [comment]
> Re-oppening since issue is only partially solved...

Good point. Thanks.
