### ISSUE TITLE
ES CRC type enumerations do not belong in cfe_mission_cfg.h

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#2174]
**Is your feature request related to a problem? Please describe.**
The mission config header file contains the following definitions:

https://github.com/nasa/cFE/blob/be88a07313ff3b579c8abaef4b4a9085e74aabdf/cmake/sample_defs/sample_mission_cfg.h#L261-L268

These enumeration values are really part of the API to the `CFE_ES_CalculateCRC()` function, as they define the values for the 4th parameter.   

They do not belong in "mission_cfg.h" because are not values that appear in any telemetry, nor in any command, nor would they need to be configured differently as there is no chance of conflict with anything else.

**Describe the solution you'd like**
Make a proper enumeration type in the in the `cfe_es_api_typedefs.h` file, and use this for the 4th parameter of the `CFE_ES_CalculateCRC()` function.

**Additional context**
The "DEFAULT" value is the only thing that (theoretically) does belong here:

https://github.com/nasa/cFE/blob/be88a07313ff3b579c8abaef4b4a9085e74aabdf/cmake/sample_defs/sample_mission_cfg.h#L281

However, this is just a placeholder anyway because only the CRC16 algorithm was ever implemented.  Unless the user also has a patched version of ES, no user can set this to anything other than CRC16 or else the system will not function correctly.  Because this is somewhat of a "dead" option, and a case could be made to remove it entirely.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by jphickey** [comment]
This was noted because when using EDS, all the mission-scope configurable items (i.e. everything in cfe_mission_cfg.h) need to be defined in an EDS so they can be referenced from EDS files and scripts.  

This enumeration stood out because it was an extraneous item defined in the C header but not actually used in the CMD/TLM interface.

**Comment by thnkslprpt** [comment]
I had a crack at this - including removal of the default option.
