### ISSUE TITLE
Add generic status code for "invalid request"

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#2258]
**Is your feature request related to a problem? Please describe.**
CFE defines several generic status codes, which are not specific to any module.  These can be used by any app/module to indicate common status conditions, for example: 
 - `CFE_SUCCESS`
 - `CFE_STATUS_NOT_IMPLEMENTED`
 - `CFE_STATUS_REQUEST_ALREADY_PENDING`
 - `CFE_STATUS_EXTERNAL_RESOURCE_FAIL`
 
However none of these are really appropriate for a validation failure for a request - e.g. if a value was out of range, or something of that nature.  

**Describe the solution you'd like**
Add the following generic status codes:
- `CFE_STATUS_VALIDATION_FAILURE`: for requests/inputs that fail structural validations; this one can also be useful with TBL validation functions.
- `CFE_STATUS_RANGE_ERROR`: for requests that pass structural validation, but an input value is outside the acceptable range.
- `CFE_STATUS_INCORRECT_STATE`: for requests that are otherwise valid, but the current system state does not permit its acceptance.

**Describe alternatives you've considered**
Each app could define these status codes, but that would be redundant as these are common validation checks that every app should be doing on its inputs, so a common status code is warranted.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by thnkslprpt** [comment]
Would help with this as well I think: https://github.com/nasa/CF/issues/57

**Comment by skliper** [comment]
I like it.  Even better if we could get to one set of status codes for cFS and a common status type provided from OSAL (extended by cFE/apps if needed).  It's a pain to manage 2 to 3 different status code types.  Maybe even consolidate error reporting and construct a default string or whatever... perror like, etc.
