### ISSUE TITLE
Timstamp all cFE generated SB messages

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#26]
**Is your feature request related to a problem? Please describe.**
SB Subscription Report message is not timestampted:

https://github.com/nasa/cFE/blob/6aaf5a3244e02af43c8ebb893ef413916dff5ef2/fsw/cfe-core/src/sb/cfe_sb_api.c#L1094-L1100

**Describe the solution you'd like**
Timestamp should be added here and anywhere else it's missing for all cFS generated SB messages:
```
CFE_SB_TimeStampMsg((CFE_SB_Msg_t *) &CFE_SB.SubRprtMsg);
```

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman/NASA-GSFC
Originated from PACE/OCI

**Comment by dzbaker** [comment]
CCB 24 October 2024: Addressed with https://github.com/nasa/cFE/issues/2467.
