### ISSUE TITLE
CFE_ES_ReloadApp() and CFE_ES_DeleteApp() missing range check on AppID

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#299]
These two functions are defined in `cfe_es.h` and therefore available for external applications and libraries to call.

These accept a passed in `AppID` parameter which is used as a table index, but they do not check the range of the value prior to using it as an array index.  If the value is out of range, this will cause undefined behavior and possibly a crash.

**Comment by skliper** [comment]
_Imported from trac issue 268.  Created by jphickey on 2019-03-27T14:04:53, last modified: 2019-08-14T14:09:06_

**Comment by skliper** [comment]
_Trac comment by jhageman on 2019-07-03 12:48:08:_

Moved unfinished 6.6.1 issues to next minor release

**Comment by skliper** [comment]
Just piling on CFE_ES_SetAppState, and likely others (needs scrub per #300)

**Comment by dmknutsen** [comment]
I finished the API scrub.  It is attached.
Also note that CFE_ES_SetAppState does not show up in the audit.  That is because it is an internal function.
[API_Audit.xlsx](https://github.com/nasa/cFE/files/4307811/API_Audit.xlsx)

**Comment by skliper** [comment]
Duplicate of #546 (complete survey of issues).
