### ISSUE TITLE
Remove references to coreflightsystem.org since it is now a malware site

### ISSUE THREAD

**Issue by mfalkvidd** [nasa/cFE#31]
**Describe the bug**
This repo has several references to coreflightsystem.org. The current owner of that domain is using it for spreading malware (I got a prompt to install a Firefox malware addon).

**To Reproduce**
1. Go to https://github.com/nasa/cFE
2. Click on the links to coreflightsystem.org
3. Get prompted to install malware, or with spam links.

**Expected behavior**
No links to malware sites

**Code snips**
Not applicable

**System observed on:**
Firefox on Chrome (probably applies to other browsers and platforms)

**Comment by skliper** [comment]
Thanks.  Missed those references in my initial repo scrub and been meaning to fix for a while.
