### ISSUE TITLE
Memory alignment issues in Table Services

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#314]
The CFE code has some problem areas for CPUs that have strict memory alignment requirements (e.g. SPARC).  Casting from a type with smaller requirements to a type with larger requirements generates a compile time warning and may induce a runtime exception if the memory actually is not aligned.

The following errors exist in the TBL subsystem:

{{{
/cfe/fsw/cfe-core/src/tbl/cfe_tbl_internal.c: In function 'CFE_TBL_RemoveAccessLink':
/cfe/fsw/cfe-core/src/tbl/cfe_tbl_internal.c:480:70: warning: cast increases required alignment of target type [-Wcast-align]
             Status = CFE_ES_PutPoolBuf(CFE_TBL_TaskData.Buf.PoolHdl, (uint32 *)RegRecPtr->Buffers[0].BufferPtr);
                                                                      ^
/cfe/fsw/cfe-core/src/tbl/cfe_tbl_internal.c:492:74: warning: cast increases required alignment of target type [-Wcast-align]
                 Status = CFE_ES_PutPoolBuf(CFE_TBL_TaskData.Buf.PoolHdl, (uint32 *)RegRecPtr->Buffers[1].BufferPtr);
                                                                          ^
}}}

NOTE: This is related to PSP ticket [cfs_psp:41]

**Comment by skliper** [comment]
_Imported from trac issue 283.  Created by jphickey on 2019-04-25T09:54:18, last modified: 2019-08-14T14:10:17_

**Comment by skliper** [comment]
Targeting 7.0 to allow major tlm packet updates. Errors don't show up in 32bit build for MCP750 with CCSDS Version 2 set so not critical to 6.8.

**Comment by jphickey** [comment]
This is already fixed in issue #437, via commit 4607e4ee

**Comment by skliper** [comment]
Fixed by #479
