### ISSUE TITLE
Remove fsw/mission_inc and fsw/platform_inc (classic build support)

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#344]
Directories are only used by classic build and duplicate defines in sample_defs.  Should be removed.

Targeted for 7.0 since it will break classic build (deprecated in 6.7).

**Comment by skliper** [comment]
_Imported from trac issue 313.  Created by jhageman on 2019-07-12T15:16:50, last modified: 2019-08-14T14:08:00_

**Comment by skliper** [comment]
@jphickey @acudmore what are our remaining dependencies on these directories?  Could one of you list them here?

**Comment by jphickey** [comment]
I don't believe CFE has any dependencies on these at all.   But sometimes apps directly include them (e.g. SAMPLE_APP or the LAB apps maybe?).  

Should be an obvious build failure if there was a dependency though.  My recommendation is to take these out, and grep for "mission_inc" or "platform_inc" globally across the code base to verify that nothing directly references it.

If those strings don't exist in any source files and the code builds and runs OK, can be pretty sure that nothing needed them.
