### ISSUE TITLE
Add flag at prep stage to OMIT_DEPRECATED

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#355]
Need an easy way for users (and the CI system) to omit all deprecated elements.  Something like

make OMIT_DEPRECATED=true prep

which would then internally add all the -DCFE_OMIT_DEPRECATED -DOSAL_OMIT_DEPRECATED and so on flags when building everything.

**Comment by skliper** [comment]
_Imported from trac issue 324.  Created by jhageman on 2019-08-23T17:07:17, last modified: 2019-08-23T17:07:17_

**Comment by skliper** [comment]
@jphickey do you have a suggestion for this one?  I quickly jammed in:
```
  # Omit deprecated elements if set
  if (OMIT_DEPRECATED)
    add_definitions(-DCFE_OMIT_DEPRECATED_6_6 -DOSAL_OMIT_DEPRECATED)
  endif (OMIT_DEPRECATED)
```
to the prepare function of mission_build.cmake so I could move forward with CI improvements locally.  Didn't cache but easy enough to add.

**Comment by jphickey** [comment]
I recommend just setting OSAL_USER_C_FLAGS when doing the initial prep, which allows one to add your own flags.

i.e. `make SIMULATION=native OSAL_USER_C_FLAGS='-DCFE_OMIT_DEPRECATED_6_6 -DOSAL_OMIT_DEPRECATED -Wall -Werror -std=c99 -pedantic' prep`

Shouldn't need to edit files.  This is how I generally test it out.  This is also cached so it is retained as part of the build tree.

**Comment by skliper** [comment]
I am really not a fan of doing it that way.  OSAL_USER_C_FLAGS is not consistently applied everywhere, I think I've either emailed you or commented somewhere about previous issues with this technique.  I'd much rather from a top level add these definitions explicitly, and not require the user or CI to know what the actual define values are.

**Comment by skliper** [comment]
See #24 for some other issues with OSAL_USER_CFLAGS.  Not a fan of `make SIMULATION=native OSAL_USER_C_FLAGS='-DCFE_OMIT_DEPRECATED_6_6 -DOSAL_OMIT_DEPRECATED -Wall -Werror -std=c99 -pedantic' prep` since a layer of abstraction (like "OMIT_DEPRECATED") means I wouldn't have to retrain users whenever a flag changes or we decide to add or remove from the warning set.  Also allows us to work towards compliance (define an initial set, and add as needed) with only requiring to update in one spot... we've discussed strict-protoypes and cast-align in the past.

**Comment by jphickey** [comment]
Yes, the top-level wrapper makefile is another place that we could put logic like this.  However it was never _required_ that projects use this wrapper, it is just a convenient way to build with a single "make" and not be concerned with the specific CMake invocation to generate your makefiles.

That being said, we probably do need to have some sort of document (or at least a paragraph in the README) that indicates the name and meaning of the various configure-time options in the build system for that version of code.

**Comment by skliper** [comment]
CCB 20191106 - discussed as high priority so simple CI improvements can move forward (matrix jobs to build both with and without deprecated elements) without hard coding defines in yml scripts
