### ISSUE TITLE
User/beginner friendly permissive mode implementation

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#358]
Failure when running as a normal user due to not setting the permissive mode should be user friendly.  Both for message queues and priorities failures.

Also requesting a command line option, or default to permissive mode for the bundle (should just work out of the box on a linux system for a new user, the bundle is not a flight distribution).  Maybe relate it to SIMULATION=native setting?  Note current way it's set up (as an #undef in default_osconfig.h precludes passing it in as an option). 

Worth discussing since currently the bundle defaults to debug mode with no optimization anyways.  Perhaps permissive mode is also appropriate?  Distribution guide (or whatever documentation is available) could cover transition to more flight-like configuration.

**Comment by skliper** [comment]
_Imported from trac issue 327.  Created by jhageman on 2019-08-27T10:10:53, last modified: 2019-08-27T10:10:53_

**Comment by skliper** [comment]
@jphickey @acudmore what's your preferred solution?  Right now the #undef requires a file edit to make it work which is undesirable from a CI point of view.  How about just change to a commented out #define, and add a prep flag like ENABLE_PERMISSIVE (and mention the prep flag in the default_osconfig.h)?

**Comment by jphickey** [comment]
In the future we had discussed moving all "code selection" options in osconfig.h to a build system config rather than putting these in a C header file.  If/When we do that then the ENABLE_PERMISSIVE build option would logically be part of that.

In the meantime, I think we might be able to buy time by changing the `#undef` to be:

```
#ifdef SIMULATION
#define OSAL_DEBUG_PERMISSIVE_MODE
#endif
```

This assumes that new users build with `SIMULATION=native` though.  Should make sure that this is in the user guide.  By default I think the users guide has one do a "cross" build (non-sim) but using the host compiler so the output is for the same architecture in the end.

**Comment by skliper** [comment]
I'm actually not a fan of mixing SIMULATION and the PERMISSIVE mode (contrary to my original comments on this ticket) since they really are unique as you have highlighed.  How about just take the setting out of osconfig.h, and do it in the build system instead of adding an intermediate step?  It can still just be a -D flag passed in, but get's me the easier configuration capability now.

If this approach is accepted, should also remove setting from:
osal/src/bsp/pc-linux/config/osconfig.h

See c19536c

**Comment by skliper** [comment]
CCB - suggest just commenting out a #define, then allows environment variable to set
- suggest evaluating on how often something changes
- Suggest code selection is in build system
  - Things like network code, etc
- Suggest build options in build system (BUILDTYPE)
   - permissive mode fits under this option, suggestion to keep it unique

**Comment by skliper** [comment]
CCB 20200115 - Discussed just adding native_osconfig.h and override the permissive mode setting, that way whenever running as SIMULATION=native the permissive mode is set.
