### ISSUE TITLE
Running core-linux.bin Startup Errors

### ISSUE THREAD

**Issue by JimKaidyNASA** [nasa/cFE#363]
The startup says the queue depth may be too large for the OS to handle.  The msg_max defaults to 10 but when trying to change it the OS does not allow msg_max file be saved in the editor.

There is another problem with CreatePipeErr.

![image](https://user-images.githubusercontent.com/52501916/65993863-0a298f80-e460-11e9-9c29-a42d1f8f58a8.png)

**Comment by skliper** [comment]
Either run as root or change msg_max to a higher number (requires root) or reduce all software bus pipes to <= 10.

Note - Please utilize the "bug" issue template and provide all requested information in the future.
