### ISSUE TITLE
Problem With CreatePipeErr

### ISSUE THREAD

**Issue by JimKaidyNASA** [nasa/cFE#364]
The App Cnt (Controller) is not starting because of a pipe problem.

![image](https://user-images.githubusercontent.com/52501916/65999004-84f7a800-e46a-11e9-9580-2c1de866f1bb.png)

**Comment by skliper** [comment]
CNT_APP startup problems are outside the scope of cFE open source support without artifacts supplied that point to a specific cFE issue.  Please use "bug" issue template if you suspect this is a cFE bug.
