### ISSUE TITLE
Test condition needs verification - cFE_FS_Decompress - insize temporary become 0

### ISSUE THREAD

**Issue by avan989** [nasa/cFE#368]
**Is your feature request related to a problem? Please describe.**
Test cases where insize might temporarily hit 0 during a normal decompression. reference issue 298. 

**Requester Info**
Anh Van, NASA Goddard.

**Comment by skliper** [comment]
From #298:

> Recommend investigation if insize might temporarily hit 0 during a normal decompression.

Need to analyze code if this could ever happen.

**Comment by skliper** [comment]
Closing as-is per @jphickey investigation and the fact its due to be externalized per #291.
