### ISSUE TITLE
Remove device driver references from code

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#408]
**Is your feature request related to a problem? Please describe.**
#377 is to remove device driver requirements, there are also references in the software.

**Describe the solution you'd like**
Remove references to device drivers, "CFE_DRV", etc from software, configuration files, documentation, etc.

For example:
https://github.com/nasa/cFE/blob/5d7d766941369b6e92a0328217e43d5fd02a8cf1/fsw/cfe-core/src/es/cfe_es_apps.c#L338-L342

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by avan989** [comment]
I can do this.
