### ISSUE TITLE
Initialize system log mode implementation doesn't match requirement cES1522

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#410]
**Is your feature request related to a problem? Please describe.**
Requirement cES1522 "Upon a Processor Reset, the cFE shall set the System Log Mode to discard."
Implementation:
https://github.com/nasa/cFE/blob/5d7d766941369b6e92a0328217e43d5fd02a8cf1/fsw/cfe-core/src/es/cfe_es_task.c#L236-L239

The build verification test just happens to pass because the sample configuration defaults the mode to discard.

**Describe the solution you'd like**
Update requirement or implementation.

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
Recommend the requirement be reworded to say "Upon a Processor Reset, the cFE shall set the System Log Mode to the platform default"

**Comment by skliper** [comment]
I should have included the rational: "Want to preserve the System Events that may have captured the cause of the processor reset."  So intent was to specifically override on a processor reset.  Definitely open for discussion...

**Comment by jphickey** [comment]
And one can achieve (or fail to achieve) the goal stated in the rationale in the rationale either way.  It is just as easy to lose the syslog information with it set to discard, as the log may have been full already when the event occurred.  At the end of the day this is just a system integration issue.  Seems pretty cut and dry to me - cfe cannot "enforce" that deployments are correctly configured.

**Comment by skliper** [comment]
It's definitely one for the architects @acudmore @jwilmot.  I'd think the vision in mind was for typical use default to overwrite for power on reset, force to discard on processor reset.  User setting to discard at power on is certainly their choice to make, for which the discard on processor reset has no effect.

**Comment by skliper** [comment]
Path forward - separate configurable default for power on and processor reset.  Default power on to overwrite and processor reset to discard.  Requirements will be updated to match (will like req issue to this one).  Users can modify however desired, but comes out of the box with the configuration that matches initial intent.

**Comment by skliper** [comment]
See cES1522 and cES1523 updates in #509
