### ISSUE TITLE
many unit tests report event count errors as hex

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/cFE#418]
**Describe the bug**
Unit tests check the number of events sent during the test, many of these in sb_UT.c are reported as hex...Such as in Test_SB_Cmds_SendPrevSubs (line 2704.)

**To Reproduce**
Uncovered when I was changing GetPipeName to produce events (as part of making it a public API) and the unit test event counts had to be updated. A simple test is to change the "ExpRtn" for a test.

**Expected behavior**
Event counts should reported in decimal.

**Code snips**
See above.

**System observed on:**
Linux VM

**Additional context**
N/A

**Reporter Info**
Christopher.D.Knight@nasa.gov

**Comment by CDKnightNASA** [comment]
In reviewing the error reporting in general, I'm wondering if we want to use some macros and some global variables rather than having so much duplicated code in each fn.

**Comment by jphickey** [comment]
Yes, I am a big fan of macro-izing many of the repetitive unit test constructs.  In particular there should be a at least macro to call a function and check its int32 return code (very common).   I have an example of such a macro in nasa/sample_lib#11

But updating all the existing test cases is extremely tedious and time consuming....

**Comment by CDKnightNASA** [comment]
> But updating all the existing test cases is extremely tedious and time consuming....

*Raises hand to volunteer to do at least sb_UT.c as a "demo"*

**Comment by jphickey** [comment]
> _Raises hand to volunteer to do at least sb_UT.c as a "demo"_
Great!!  No complaints from me about that!

**Comment by CDKnightNASA** [comment]
Point of interest: my sample of sb_UT.c went from 10,487 lines of code to 6,878 lines, a roughly 35% reduction in code size for the UT. Check it out! :D

**Comment by CDKnightNASA** [comment]
@skliper would like to review the sb_UT.c changes at an upcoming CCB meeting.

**Comment by skliper** [comment]
@CDKnightNASA could you write an issue (Macro-ize unit test enhancement) and go ahead and put your changes in as a pull request to facilitate review?

**Comment by CDKnightNASA** [comment]
> @CDKnightNASA could you write an issue (Macro-ize unit test enhancement) and go ahead and put your changes in as a pull request to facilitate review?

see https://github.com/nasa/cFE/pull/492

**Comment by skliper** [comment]
Fixed in #698
