### ISSUE TITLE
lgtm issue

### ISSUE THREAD

**Issue by avan989** [nasa/cFE#431]
**Describe the bug**

cfe_es_perf.c

```
if ((CmdPtr->TriggerMode >= CFE_ES_PERF_TRIGGER_START) && (CmdPtr->TriggerMode < CFE_ES_PERF_MAX_MODES))
--
  | Pointless comparison of unsigned value to zero.

```

cfe_fs_decompress.c

```
line: 686
if ( index >= 0  &&  index < State->hufts )
--
  | Pointless comparison of unsigned value to zero.


line 733
if ( index >= 0  &&  index < State->hufts )
--
  | Pointless comparison of unsigned value to zero.

```

cfe_es_perf.c

/* enable interrupts */
```
--
491 | OS_IntUnlock(IntFlags);
  | This expression has no effect (because OS_IntUnlock has no external side effects).
492 | }
493 | }

```

cfe_sb_task.c

```
if(CFE_PLATFORM_EVS_MAX_EVENT_FILTERS < CfgFileEventsToFilter){
--
  | Comparison is always false because 4 >= CfgFileEventsToFilter.

```

cfe_tbl_internal.c

```
line 196:
(Status >= CFE_PLATFORM_TBL_MAX_SNGL_TABLE_SIZE));
--
  | Comparison is always true because Status >= 16384.
197 | }
```

cfe_time_api.c

```
line 679:
if (ConvertFactor < 0)
--
  | Comparison is always false because ConvertFactor >= 789004800.
```

**To Reproduce**
1. Build against lgtm

**Reporter Info**
Anh Van, NASA Goddard

**Comment by skliper** [comment]
Note using clang the index >= 0 comes up as a warning, and will fail if built with -Werror.

**Comment by skliper** [comment]
cfe_sb_api issue - CFE_PLATFORM_SB_MAX_DEST_PER_PKT description says:
`Destination number values that are checked against this configuration are defined by a 16 bit data word.`

The event buffer is only added to up to once per destination (Destinations is uint16 in CFE_SB_RouteEntry_t), so EvtsToSnd uint32 can be changed to uint16 to avoid this warning.

**Comment by skliper** [comment]
OBE - new issues will be opened for any current LGTM warnings that require resolution.
