### ISSUE TITLE
Improve API consistency for functions accepting a software bus message

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#440]
**Is your feature request related to a problem? Please describe.**
The data types accepted by the SB API are not entirely consistent.  Most API functions that operate on software bus message buffers accept a `CFE_SB_MsgPtr_t`.

There are some exceptions, most notably the `CFE_SB_InitMsg()` function accepts a `void*`.

**Describe the solution you'd like**
All SB API functions that operate on message buffers should use the `CFE_SB_MsgPtr_t` type (or `CFE_SB_Msg_t *`)

**Additional context**
Making the interface type-correct helps the compiler's type checking do its intended job, helping to catch/avoid the possibility of passing a data buffer which is not actually an SB message buffer.  Using `void*` permits anything to be passed in, effectively disabling all checking.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment]
CFE_SB_InitMsg was deprecated in #998, no remaining instances found of using void * with msg.
