### ISSUE TITLE
Incomplete coverage test for cfe_es_api.c

### ISSUE THREAD

**Issue by avan989** [nasa/cFE#465]
**Is your feature request related to a problem? Please describe.**
current coverage: 97.7 %
Missing coverage for the following:

CFE_ES_SetAppState

```
     197             :         /* Caller error - invalid state */
     198           0 :         return;
```

CFE_ES_ReloadApp

```
     314           0 :            CFE_ES_SysLogWrite_Unsync ("CFE_ES_ReloadApp: Cannot Reload Application %s, File %s does not exist.\n",
     315           0 :                                   CFE_ES_Global.AppTable[AppID].StartParams.Name,
     316             :                                   AppFileName);
     317           0 :            ReturnCode = CFE_ES_FILE_IO_ERR;
```

CFE_ES_ExitApp

```
     471           0 :           CFE_ES_SysLogWrite_Unsync ("Application %s called CFE_ES_ExitApp\n",
     472           0 :                                  CFE_ES_Global.AppTable[AppID].StartParams.Name);
     473           0 :           CFE_ES_SetAppState(AppID, CFE_ES_AppState_STOPPED);
     474             : 
     475             :           /*
     476             :           ** Unlock the ES Shared data before suspending the app 
     477             :           */
     478           0 :           CFE_ES_UnlockSharedData(__func__,__LINE__);
     479             : 
     480             :           /*
     481             :           ** Suspend the Application until ES kills it.
     482             :           ** It might be better to have a way of suspending the app in the OS
     483             :           */
     484             :           while(1)
     485             :           {
     486           0 :              OS_TaskDelay(500);
```

CFE_ES_DeleteChildTask

```
    1272           0 :        CFE_ES_WriteToSysLog("CFE_ES_DeleteChildTask Error: Invalid Task ID: %u\n",(unsigned int)OSTaskId );
    1273           0 :        ReturnCode = CFE_ES_ERR_TASKID;
```

CFE_ES_GetAppIDInternal

`    1758           0 :       *AppIdPtr = 0;`

**Requester Info**
Anh Van, NASA Goddard

**Comment by pepepr08** [comment]
`CFE_ES_SetAppState` no longer in cfe_es_api.c

**Comment by pepepr08** [comment]
`CFE_ES_ReloadApp` tests are outdated. Comments don't match the actual test. I will be adding new tests for the whole function.

**Comment by pepepr08** [comment]
Testing `CFE_ES_ExitApp` involves an infinite loop. This will be handled separately.

**Comment by skliper** [comment]
> Testing `CFE_ES_ExitApp` involves an infinite loop. This will be handled separately.

Could you write a separate issue for any infinite loops you encounter?  These will be addressed separately.  This issue can be closed once the coverage possible with the current implementation is achieved.

**Comment by pepepr08** [comment]
For `CFE_ES_DeleteChildTask`, the "invalid Invalid Task ID" error case was already being covered but code will be added to cover the "Task ID is not active" error case.

**Comment by pepepr08** [comment]
`CFE_ES_GetAppIDInternal` has been removed, but UT code will be added to cover the null case on `CFE_ES_GetAppID`, `CFE_ES_GetAppIDByName` and `CFE_ES_RegisterCDS`

**Comment by pepepr08** [comment]
> > Testing `CFE_ES_ExitApp` involves an infinite loop. This will be handled separately.
> 
> Could you write a separate issue for any infinite loops you encounter? These will be addressed separately. This issue can be closed once the coverage possible with the current implementation is achieved.

Created #1628 for infinite loop test case in `CFE_ES_ExitApp`
