### ISSUE TITLE
Maximum number of cFE instances?

### ISSUE THREAD

**Issue by SweeWarman** [nasa/cFE#501]
This is not a bug, but a question related to cFE usage:
We are currently trying to perform multi-agent simulations using applications developed on the cFE middle-ware. A single agent is launched by running the core executive. However, we are not able to launch more than 7 instances of cFE on a single linux machine. The 8th instance of cFE throws errors: "CreatePipeErr: OS_QueueCreateErr returned -1" Please see attached image. Are there any parameters that could be changed to enable more instances of cFE to run on a single machine? 

Changing the default values of OS_MAX_QUEUES, CFE_PLATFORM_SB_MAX_PIPES didn't seem to help.

![CreatePipeErr](https://user-images.githubusercontent.com/7516618/73398738-00038a80-42b4-11ea-8a5a-a9b7e9c56a1a.png)

**Reporter Info**
NIA/NASA Langley

**Comment by skliper** [comment]
What's the current limit on your system?  check /proc/sys/fs/mqueue/queues_max.  Maybe force it to a bigger number?  

root# echo 1028 > /proc/sys/fs/mqueue/queues_max
