### ISSUE TITLE
Executive Services Requirements Scrub - Missing command requirements

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#512]
**Is your feature request related to a problem? Please describe.**
ES requirements out of date

**Describe the solution you'd like**
Update requirements

**Describe alternatives you've considered**
N/A

**Additional context**
Note #509 and #510 missed the following new commands.

New command requirements:
- cES1029: CFE_ES_StartPerfDataCmd
- cES1030: CFE_ES_SetPerfFilterMaskCmd
- cES1031: CFE_ES_SetPerfTriggerMaskCmd
- cES1032: CFE_ES_QueryAllTasksCmd
- cES1033: CFE_ES_SendMemPoolStatsCmd

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
PR #526 includes this fix
