### ISSUE TITLE
Table Services Requirements Scrub

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#513]
**Is your feature request related to a problem? Please describe.**
TBL requirements out of date

**Describe the solution you'd like**
Update requirements

**Describe alternatives you've considered**
N/A

**Additional context**
Summary of changes (w/ links if individual issues exist already):
- cTBL6011 - HK requirement not consistent (update wording)
- cTBL6301 - Free app resources handled by ES_AppExit, delete
**- cTBL6700 - Maximum tables (delete, mission config)**
**- cTBL6701 - Maximum simultaneous loads and dumps (delete, mission config)**
- NEW API Requirements:
    - cTBL6313: CFE_TBL_Validate
    - cTBL6314: CFE_TBL_DumpToBuffer
    - cTBL6315: CFE_TBL_Modified cfe-999
    - cTBL6316: CFE_TBL_Manage cfe-995
- NEW Cmd Requirements:
    - cTBL6013: CFE_TBL_DeleteCDSCmd
    - cTBL6013.1: Delete CDS - Table In Use
    - cTBL6013.2: Delete CDS - Not Critical Table
    - cTBL6013.3: Delete CDS - Already Deleted

**Requester Info**
Jacob Hageman - NASA/GSFC

*EDIT* - Bold items missed in first round

**Comment by astrogeco** [comment]
Closing since PR #526 includes this fix
