### ISSUE TITLE
Event Services Requirements Scrub

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#516]
**Is your feature request related to a problem? Please describe.**
EVS requirements out of date

**Describe the solution you'd like**
Update requirements

**Describe alternatives you've considered**
N/A

**Additional context**
Summary of changes (w/ links if individual issues exist already):
- cEVS3018 - HK requirement not consistent (update wording)
- cEVS3103.3.1 - filter counter configurable max (change from hard number)
- cEVS3110 - free app resources, done by ES_AppExit (delete EVS req)
- cEVS3200 - initialize ports default config per port (delete, psp/hardware configuration #93 #94)
- cEVS3201 - power on event format configurable (change from long)
- cEVS3207 - preserve log mode on processor reset (clarify requirement, just wording update)
- cEVS3209 - Processor reset default log mode (delete, conflicts with 3207)
- cEVS3300 - support # of message ports (delete, psp/hardware dependent #93 #94)
- cEVS3301 - Event Log Size (delete, mission config)
- cEVS3302 - # of event filters per app (delete, mission config)
- NEW API Requirements:
    - None
- NEW Cmd Requirements:
    - None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
Closing since PR #526 includes this fix
