### ISSUE TITLE
Time Services Requirements Scrub

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#518]
**Is your feature request related to a problem? Please describe.**
TIME requirements out of date

**Describe the solution you'd like**
Update requirements.  

NOTE 1 - this is not major reworking of the requirements/design (#302), but focused on just bringing the requirements up to date.  Future issues will address significant development/rework.

NOTE 2 - MET functionality still applies here (not all abstracted to PSP) to support the virtual MET capability (hardware MET is not required).

**Describe alternatives you've considered**
N/A

**Additional context**
Summary of changes (w/ links if individual issues exist already):
- cTIME2000- HK requirement not consistent (update wording)
- cTIME2001 - wording scrub, remove "time server and time client" inconsistent pattern
- cTIME2002 - wording scrub, remove "time server and time client" inconsistent pattern
- cTIME2007 - Update summary, it's really compute SCTF given current time
- cTIME2008 - adjust CTF requirement (delete, redundant with add/subtract requirements)
- cTIME2010 - summary: select tone signal source, of PRIMARY vs REDUNDANT (although not explicitly defined), SetSignalCmd
- cTIME2012 - force to flywheel (not just flywheel), then will not update time based on Tone Data/Signal.
- cTIME2012.1 - propagates MET locally (update wording), uses internal best guess for MET.
- cTIME2013 - remove "second and subsecond", overdetailed and wrong, really SCTF
- cTIME2014 - remove "second and subsecond", overdetailed and wrong, really SCTF
- cTIME23XX - all requests remove extra language (format specified)
- cTIME2701 - time at tone window not handled by TS (delete, hardware), sent by request/cmd
- cTIME2702 - update MET (delete generic functionality requirement, PSP/hardware)
- cTIME2703 - MET resolution (delete, PSP/hardware)
- NEW API Requirements:
    - cTIME2315 - Provide time at tone message functionality given MET, provide in message like HK
    - cTIME2316 - Tone Data given GPS
    - cTIME2317 - Tone Data given Time
    - cTIME2318 - Register synch callback (callback at Tone Signal receipt)
    - cTIME2319 - unregister synch callback  (UnregisterSynchCallback)
    - cTIME2320 - get clock info state flags for TIME (GetClockInfo)
    - cTIME2321 - convert a given MET to SC Time (MET2SCTime)
    - cTIME2322 - Local1HzISR, API to trigger 1 HZ processing
    - cTIME2323 - ExternalTone, API to trigger Tone processing
- NEW Cmd Requirements:
    - cTIME2012.2 - External Time Update Mode - Use Updates (update timekeeping when Tone Signal and Data pair are received)
    - cTIME2015 - ToneSendCmd just sends Tone Data message (no time update)
    - cTIME2016 - ToneData (Cmd), triggers receipt of Tone Data processing
    - cTIME2017 - ToneSignal (Cmd), triggers Tone signal processing
    - cTIME2018 - OneHz (Cmd), triggers 1Hz cycle processing
    - cTIME2019 - set MET, sets abstract MET (not hardware met), SetMETCmd
    - cTIME2020 - (AddDelayCmd)
    - cTIME2021 - (SubDelayCmd)
- NOTE: CFE2FSSeconds/FS2CFESeconds deleted per #519 
- NOTE: SetSourceCmd due refactor/fix per #302

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
Closing since PR #526 includes this fix
