### ISSUE TITLE
Software Bus Requirements Scrub

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#522]
**Is your feature request related to a problem? Please describe.**
SB requirements out of date

**Describe the solution you'd like**
Update requirements.  

**Describe alternatives you've considered**
N/A

**Additional context**
Summary of changes (w/ links if individual issues exist already):
- cSB4000 - NOOP command out of family, make consistent with other services
- cSB4005 - HK message out of family, make consistent with other services
- cSB4300 - Zero copy general requirement reads like level 4, delete and replace with API requirements
- cSB4305.6 - Max message size just clarify wording (mission config parameter)
- cSB4310 - Free app resources (done by ES_AppExit, delete from SB/API)
- cSB4700: max message ID’s (delete)
- cSB4701: sb maximum size (delete)
- cSB4704: max destinations (delete)
- cSB4705: Maximum pipes (delete)
- cSB4706: maximum pipe depth (delete)
- NEW API Requirements:
    - cSB4311- CFE_SB_GetMsgId
    - cSB4312- CFE_SB_SetMsgId
    - cSB4313- CFE_SB_MessageStringGet
    - cSB4314- CFE_SB_MessageStringSet
    - cSB4315- CFE_SB_InitMsg
    - cSB4315.1 - Clear message contents and sequence counter
    - cSB4315.2 - Retain message contents and sequence counter
    - cSB4316- CFE_SB_GetUserData
    - cSB4317- CFE_SB_GetUserDataLength
    - cSB4318- CFE_SB_SetUserDataLength
    - cSB4319- CFE_SB_GetTotalMsgLength
    - cSB4320- CFE_SB_SetTotalMsgLength
    - cSB4321- CFE_SB_GetMsgTime
    - cSB4322- CFE_SB_SetMsgTime
    - cSB4323- CFE_SB_TimeStampMsg
    - cSB4324- CFE_SB_GetCmdCode
    - cSB4325- CFE_SB_SetCmdCode
    - cSB4326- CFE_SB_GetChecksum
    - cSB4327- CFE_SB_GenerateChecksum
    - cSB4328- CFE_SB_ValidateChecksum
    - cSB4329- CFE_SB_SetPipeOpts
    - cSB4330- CFE_SB_GetPipeOpts
    - cSB4331- CFE_SB_SubscribeLocal
    - cSB4332- CFE_SB_Subscribe
    - cSB4333- CFE_SB_UnsubscribeLocal 
    - cSB4334- CFE_SB_PassMsg
    - cSB4335- CFE_SB_MsgId_Equal
    - cSB4336- CFE_SB_MsgIdToValue
    - cSB4337- CFE_SB_ValueToMsgId
    - cSB4338- CFE_SB_GetPipeName (related to #210)
    - cSB4339- CFE_SB_GetPipeIdByName (related to #210)
    - cSB4340- CFE_SB_ZeroCopyGetPtr
    - cSB4341- CFE_SB_ZeroCopyReleasePtr
    - cSB4342- CFE_SB_ZeroCopySend
    - cSB4343- CFE_SB_ZeroCopyPass
- NEW Cmd Requirements:
    - cSB4009 - Upon receipt of valid command increment command counter
    - cSB4010 - Upon receipt of invalid command increment command error counter
    - cSB4011- CFE_SB_EnableSubReportingCmd 549
    - cSB4012- CFE_SB_DisableSubReportingCmd 550
    - cSB4013- CFE_SB_SendPrevSubsCmd 564

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
Closing since PR #526 includes this commit
