### ISSUE TITLE
SB subscription reporting request messages out of family

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#523]
**Is your feature request related to a problem? Please describe.**
CFE_SB_EnableSubReportingCmd, CFE_SB_DisableSubReportingCmd, CFE_SB_SendPrevSubsCmd are processed like commands but don't increment the command counter.

Typical pattern is for non-ground, inter-app messages to have separate message IDs from ground commands.

**Describe the solution you'd like**
Make consistent with standard pattern

**Describe alternatives you've considered**
None

**Additional context**
See Hk message processing, or the message processing in Time services that don't increment command counter.

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by skliper** [comment]
@CDKnightNASA @tngo67 Does SBN or SBNg use these?  Since they are from another app, preference would be to not use the ground command MID.  Can we coordinate a change?

**Comment by jwilmot** [comment]
As I recall these were for SBN to use when interfacing with SB. They are not ground commands. SBN is designed to be (as best we could) a plug-in just like any other apps. We wanted to avoid call backs or other compile/link time hooks.  That said, the internal MID are in the same name space as "regular" commands so need to be allocated and managed but not in the ground system database. They should not increment the command counter +/- as those are for operators, but should send an event if an error occurs.

**Comment by skliper** [comment]
I think you are saying they should be a separate MID from the ground commands?  Want them to use the same MID (CFE_SB_SUBSCRIPTION_RPT_CONTROL_MID or whatever), or each use their own?

**Comment by CDKnightNASA** [comment]
> As I recall these were for SBN to use when interfacing with SB. They are not ground commands. SBN is designed to be (as best we could) a plug-in just like any other apps. We wanted to avoid call backs or other compile/link time hooks. That said, the internal MID are in the same name space as "regular" commands so need to be allocated and managed but not in the ground system database. They should not increment the command counter +/- as those are for operators, but should send an event if an error occurs.

Nope, SBN listens for events that are generated by subscription activity:

```
    Status = CFE_SB_SubscribeLocal(CFE_SB_ALLSUBS_TLM_MID, SBN.SubPipe,
...
    Status = CFE_SB_SubscribeLocal(CFE_SB_ONESUB_TLM_MID, SBN.SubPipe,
```

**Comment by skliper** [comment]
So who/what sends the referenced commands?

**Comment by CDKnightNASA** [comment]
> So who/what sends the referenced commands?

Sorry, looking through the code, SBN does send the relevant commands. I was looking for direct calls to the API.

**Comment by jwilmot** [comment]
The required SBN behavior is to requests subscriptions when it is done initializing the subnetwork and discovered peers. This can happen any time after local system init or later due to fault management restarting SBN. This decouples SBN from the local system. The internal commands  CFE_SB_EnableSubReportingCmd, CFE_SB_DisableSubReportingCmd, CFE_SB_SendPrevSubsCmd support this. Like other internal commands, the counters should not increment but error events should be sent. Sorry I am being dense, but it's still not clear what problem this ticket is trying to solve.

**Comment by skliper** [comment]
Discussed w/ @jwilmot and got concurrence with the following approach.

Inter-app messages/MIDs:
CFE_SB_SEND_HK_MID - For scheduler to request HK message
CFE_SB_SUBSCRIPTION_RPT_CONTROL_MID - Use for these three commands

Ground command MID:
CFE_SB_CMD_MID - ground commands only

So it'll require a 1 line change in SBN, but provides separation between the inter-app and ground commands (preferred model).

**Comment by juliejohn015** [comment]
[Subscription Reporting](https://www.subscriptionflow.com/subscription-analytics-reporting/) and Analytics Software
