### ISSUE TITLE
Document deprecated elements

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#556]
Looks like template broke... anyways:

Add \deprecated and \name the group where appropriate relative to the user's guide documentation such that it shows up as deprecated.

Jacob Hageman - NASA/GSFC

**Comment by skliper** [comment]
Suggest commenting the code typically provides a replacement or alternative where appropriate.

**Comment by skliper** [comment]
\name didn't work so well, follow doxygen deprecation pattern established in OSAL.  Suggest adding "DEPRECATED" at the start of the brief for every element that is deprecated (so it's obvious even if just the brief is shown).

**Comment by skliper** [comment]
@lbleier-GSFC - did you intend to reference this issue from your commits?  Or #559?  Or does it fix both (if so it should reference both)

**Comment by lbleier-GSFC** [comment]
> @lbleier-GSFC - did you intend to reference this issue from your commits? Or #559? Or does it fix both (if so it should reference both)

Whoops. This was supposed to be #559

**Comment by skliper** [comment]
OBE/Duplicated of other deprecation work. Any newly deprecated elements should include @deprecated flag.
