### ISSUE TITLE
Consolidate CDS and generic/ram mempool code into single implementation

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#56]
Currently there are two memory pool implementations in ES:

* cfe_es_cds_mempool.c
* cfe_esmempool.c

These two are very similar except that the CDS uses offsets rather than direct pointers, and it calls into the PSP to perform actual read/write functions.  It would not be very hard to consolidate these into a single implementation.

Each implementation consumes about 4-5kB of code/data space so this consolidation would make ES a little smaller in addition to making it cleaner.

**Comment by skliper** [comment]
_Imported from trac issue 25.  Created by jphickey on 2015-01-21T13:33:26, last modified: 2019-03-01T15:27:58_

**Comment by skliper** [comment]
_Trac comment by jphickey on 2015-05-19 09:39:35:_

This is an old enhancement that is yet to be merged in.  Higher priority items taking precedence right now.

**Comment by jphickey** [comment]
With recent addition of a generic (offset-based) memory pool implementation that works with the abstract resource IDs in #917.  I have also tested that this works for CDS blocks too.  Discussed at 2020-09-30 CCB that this would be a good time to finally do this and make one mempool implementation.
