### ISSUE TITLE
Deprecate all CFE_OS error codes

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#580]
**Is your feature request related to a problem? Please describe.**
See discussion on #552, CFE_OS error codes are an unnecessary abstraction.  No plan to translate between the two, so no need to abstract.

**Describe the solution you'd like**
Deprecate and just use the OSAL error codes directly.

**Describe alternatives you've considered**
See discussion in #552 

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by ejtimmon** [comment]
FM uses CFE_OS_ERROR.
