### ISSUE TITLE
Unit test - split "AND"-ed conditionals into separate asserts

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#596]
**Is your feature request related to a problem? Please describe.**
Debugging unit tests can be very difficult, frustrating, and time consuming.  One major part of the problem which makes them very debugging-unfriendly is something like the following:

```
    UT_Report(__FILE__, __LINE__,
              UT_EventIsInHistory(CFE_ES_PCR_ERR2_EID) &&
              CFE_ES_Global.AppTable[Id].ControlReq.AppTimer == 0 &&
              CFE_ES_Global.AppTable[Id].ControlReq.AppControlRequest == CFE_ES_RunStatus_SYS_DELETE,
              "CFE_ES_ScanAppTable",
              "Waiting; process control request");
```

The problem with this type of construct is that there are 3 separate tests being combined into one single assert.  When it fails, it is not possible to see which of the three conditions are evaluating false.  Many of them call functions within the test case, too, which further obfuscate what the actual return value was.  The only way to test this is run it in a debugger, break at the start of the test, then set a breakpoint inside e.g. UT_EventIsInHistory to see what it returned.

**Describe the solution you'd like**

1. At a minimum - split the `&&` conditions into separate asserts.  This would _at least_ let the developer know which one is actually the fault.  
2. Nice to have - employ the macros similar to what @CDKnightNASA added in nasa/osal#405, which show the _values_ tested in the log, not simply just a pass/fail.

**Describe alternatives you've considered**
Continue struggling to figure out what actually went wrong every time a UT failure comes up.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment]
Added milestone, targeted for this round for unit test consistency.

**Comment by CDKnightNASA** [comment]
Now that the UT macros for OSAL have been accepted I can take a look at using that model for CFE as well (I have a crack at sb_UT.c but I like the OSAL macros even more so I will revisit.)

**Comment by jphickey** [comment]
In order to cross reference/validate that the test cases are covering the documented functions, need to do a scrub of all "Report" outputs and make them use the proper macros that include full context info.
