### ISSUE TITLE
CFE_EVS_SendEvent stub should provide full context

### ISSUE THREAD

**Issue by gilliganeric** [nasa/cFE#603]
**Describe the bug**
The CFE_EVS_SendEvent stub for ut-assert does not provide its full context. It only provides the first argument, EventId, providing no way to for unit tests to verify the correct EventType or event message text was sent.

**To Reproduce**
1. See the [CFE_EVS_SendEvent stub](https://github.com/nasa/cFE/blob/60a5f6580d1e737f46efce0418aba5b8dac6df6a/fsw/cfe-core/ut-stubs/ut_evs_stubs.c#L106). Only EventID is registered with the context and copied. 

**Expected behavior**
The CFE_EVS_SendEvent stub should provide its full context for unit testing purposes, including the EventID, EventType, and the event message string. <strike>My preference would be that the event message text provided would not include the format specifiers and instead be the resulting string with the format specifiers replaced with the appropriate text.</strike> I've been convinced and also talked myself out of that preference.

**Code snips**
```
int32 CFE_EVS_SendEvent(uint16 EventID,
                        uint16 EventType,
                        const char *Spec,
                        ...)
{
    int32 status;

    UT_Stub_RegisterContext(UT_KEY(CFE_EVS_SendEvent), &EventID);
    status = UT_DEFAULT_IMPL(CFE_EVS_SendEvent);

    if (status >= 0)
    {
        UT_Stub_CopyFromLocal(UT_KEY(CFE_EVS_SendEvent), (uint8*)&EventID, sizeof(EventID));
    }

    return status;
}
```

**System observed on:**
 - cFE 6.7.11

**Additional context**
n/a

**Reporter Info**
Eric Gilligan NASA/GSFC-5820

**Comment by gilliganeric** [comment]
Thinking about this more, I'd also be fine with the Context getting the string as passed into `CFE_EVS_SendEvent` with the format specifiers still in it, as long as the extra arguments are put into the Context as well.

**Comment by skliper** [comment]
I think @jphickey has examples for getting format and arguments.

**Comment by jphickey** [comment]
Yes, this stub will need an update to pass through more context if UT test cases need this.

The framework has the facility to do this, via the `UT_DefaultStubImplWithArgs` routine, which can pass through the full context in a va_list to a hook implementation.   Then in the hook implementation one can do whatever is needed.

I'd still recommend against passing it to [v]snprintf, as that is now crossing the bridge of no longer validating the direct outputs of the unit, but rather mimicking/duplicating something that the FSW might do and validating that.  Very different thing.  (stubs shouldn't duplicate FSW logic).

**Comment by gilliganeric** [comment]
I agree. Disregard that preference in the original description. 

Would this look like `ArgPtr`'s last element in the hook function's `UT_StubContext_t` being a `va_list` containing the variable number of arguments?

**Comment by AlanSGibson** [comment]
I completely agree with not passing it to [v]snprintf, but I would like to see the default implementation of the CFE_EVS_SendEvent stub make the arguments available for checking without having to use a hook.

**Comment by jphickey** [comment]
The "Fixed" arguments, up to and including the spec string, can be registered using calls to `UT_Stub_RegisterContext()`.

The use `va_start` to capture all the remaining variable arguments, and invoke `UT_DefaultStubImplWithArgs` with va list as the final argument, then do `va_end` after it returns.

For an example of a stub that uses this mechanism, see `OS_printf` in: https://github.com/nasa/osal/blob/master/src/ut-stubs/osapi-utstub-printf.c

Usage with hook function example is in sample_lib: https://github.com/nasa/sample_lib/blob/master/unit-test/coveragetest/coveragetest_sample_lib.c

**Comment by skliper** [comment]
20200415 - Ok to add and pass it through

**Comment by skliper** [comment]
@gilliganeric - can you confirm #673 does what you need, or clarify what would still be necessary?

**Comment by ericgilligan-nasa** [comment]
It looks like #673 provides the Event Type and Spec, but not the variable arguments as a va_list as described by @jphickey earlier. Is that correct?

**Comment by skliper** [comment]
Correct, we can leave this open until that's implemented:

> The use `va_start` to capture all the remaining variable arguments, and invoke `UT_DefaultStubImplWithArgs` with va list as the final argument, then do `va_end` after it returns.
> 
> For an example of a stub that uses this mechanism, see `OS_printf` in: https://github.com/nasa/osal/blob/master/src/ut-stubs/osapi-utstub-printf.c
> 
> Usage with hook function example is in sample_lib: https://github.com/nasa/sample_lib/blob/master/unit-test/coveragetest/coveragetest_sample_lib.c

**Comment by jphickey** [comment]
Ahh yes, sorry I overlooked that during my review of the change.  If you want to have the actual data available in your hook this needs to use the `UT_DefaultStubImplWithArgs()` function to pass them all through.
