### ISSUE TITLE
CFE_SB_GetLastSenderID returns pointer to internal data, possible race

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#608]
**Describe the bug**
CFE_SB_GetLastSenderID returns pointer to data that could be overwritten at any time

See https://github.com/nasa/cFE/pull/605#discussion_r407649126 for related comments

**To Reproduce**
Conceptually - app calls CFE_SB_GetLastSenderID, gets pointer, data gets overwritten, app takes action based on overwritten data vs original context

**Expected behavior**
No race.

**Code snips**
https://github.com/nasa/cFE/blob/60a5f6580d1e737f46efce0418aba5b8dac6df6a/fsw/cfe-core/src/sb/cfe_sb_api.c#L1651-L1657

**System observed on:**
N/A

**Additional context**
#605

**Reporter Info**
Jacob Hageman

**Comment by skliper** [comment]
Ping @CDKnightNASA @tngo67 and any other user's of this API (SBN related?)

**Comment by astrogeco** [comment]
See https://github.com/nasa/cFE/pull/816
