### ISSUE TITLE
OSAL coverage report includes unit tests

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#614]
**Is your feature request related to a problem? Please describe.**
Coverage numbers include the actual unit test code

**Describe the solution you'd like**
Exclude unit test code from coverage results

**Describe alternatives you've considered**
None

**Additional context**
nasa/osal#404

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
Shouldn't really need to do anything for this; the issue will likely go away with the next cycle anyway

**Comment by skliper** [comment]
Confirmed issue no longer exists.
