### ISSUE TITLE
CFE TLM header needs update to correspond with CMD header

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#628]
Previous issue #297 made it so the CMD secondary header was always in a consistent byte order, such that the content is independent of the endianness of the machine which processes/generates the packet.

The submitted fix for this only changed the CMD header, leaving the TLM header alone.  

For consistency, the network byte order rule should be applied to the TLM header as well.

_Originally posted by @jphickey in https://github.com/nasa/cFE/issues/297#issuecomment-595435305_

**Comment by skliper** [comment]
See #92
