### ISSUE TITLE
CFE needs to provide CMake-based config file for OSAL

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#652]
**Is your feature request related to a problem? Please describe.**
Currently the CFE cmake script generates an `osconfig.h` file for OSAL to compile with.

**Describe the solution you'd like**
After nasa/osal#285 is fixed (PR nasa/osal#427) the CFE will need to  pass OSAL a configuration file in CMake syntax, which then OSAL uses to generate its own `osconfig.h`.

**Additional context**
Needed for compatibility

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by jtovias** [comment]
@jphickey , I'm trying to override OS_MAX_FILE_NAME, how do I update OS_MAX_FILE_NAME in native_osconfig.cmake?

**Comment by jtovias** [comment]
@jphickey figured it out. have to set OSAL_CONFIG_MAX_FILE_NAME.
