### ISSUE TITLE
Missing registering contexts in stub functions

### ISSUE THREAD

**Issue by jtovias** [nasa/cFE#657]
I’ll work this issue

The issue causes seg faults cause by not registering contexts. I resolved this by adding the missing registrations.
 

cfe/fsw/cfe-core/ut-stubs/ut_evs_stubs.c:
int32 CFE_EVS_SendEvent(uint16 EventID,
                        uint16 EventType,
                        const char *Spec,
                        ...)
{
    int32 status;
    UT_Stub_RegisterContext(UT_KEY(CFE_EVS_SendEvent), &EventID);
    UT_Stub_RegisterContext(UT_KEY(CFE_EVS_SendEvent), &EventType);  <----- missing
    UT_Stub_RegisterContext(UT_KEY(CFE_EVS_SendEvent), Spec);              <----- missing
..
}
 
cfe/fsw/cfe-core/ut-stubs/ ut_es_stubs.c:
int32 CFE_ES_WriteToSysLog(const char *pSpecString, ...)
{
    int32   status;
    UT_Stub_RegisterContext(UT_KEY(CFE_ES_WriteToSysLog), pSpecString);  <----- missing
 ...}

Expected behavior
Return register buffer size=3 when using CFE_EVS_SendEvent and buffer size =1 when using CFE_ES_WriteToSysLog.

System observed on:

Hardware
OS: Centos 7
Versions:cFE 6.7.12.0, OSAL 5.0.11.0, PSP 1.4.8.0, chksm 9194

Reporter Info
Jose Tovias CACI/LZT Technology

**Comment by jtovias** [comment]
@skliper , Do I make a branch from development and call it fix657-add-UT-Stub_RegisterContext?

**Comment by skliper** [comment]
@jtovias - I was just marking that you already fixed it in #673, marking is more for internal documentation/compliance and VDD generation at release time
