### ISSUE TITLE
remove conditional TBL compilation logic

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/cFE#680]
**Is your feature request related to a problem? Please describe.**
With #660 TBL is no longer optional; conditional code/compilation configuration should be removed.

**Requester Info**
Christopher.D.Knight@nasa.gov

**Comment by skliper** [comment]
Also remove the conditional description in the doxygen documentation: 
https://github.com/nasa/cFE/blob/8365a0c69b810e313afe0fe19cdc8987374621e3/docs/src/cfe_tbl.dox#L31-L62

**Comment by jphickey** [comment]
Note - as part of fixing #950 I'm rearranging some of the cleanup logic, and the call to `CFE_TBL_CleanUpApp()` is currently conditional on `EXCLUDE_CFE_TBL`.  I'd like to drop the `#ifdef` here as part of my upcoming change.

Here is the `#ifdef` I want to remove:
https://github.com/nasa/cFE/blob/dc3d62b37d2bacd8fe23f66ff7b64025ac7d0751/fsw/cfe-core/src/es/cfe_es_apps.c#L1104-L1106

There are two other places it appears in `cfe_es_objtab.c` which would still need to be cleaned up, assuming we go through with this for 7.0

**Comment by skliper** [comment]
Note if we update to the services being modules, tbl removal/customization comes almost for free (still need to remove all the EXCLUDE_CFE_TBL occurrences).  Could just make non-ops for the few calls that do exist, or customize/replace whatever is desired and replace the core module.  Related to #972.
