### ISSUE TITLE
Doxygen warnings

### ISSUE THREAD

**Issue by lbleier-GSFC** [nasa/cFE#681]
**Describe the bug**
Doxygen warnings due to lack of documentation in the following files:

- `cFS/cfe/fsw/cfe-core/src/tbl/cfe_tbl_internal.c`
- `cFS/cfe/fsw/cfe-core/src/tbl/cfe_tbl_internal.h`

Specifically for function `CFE_TBL_LoadFromFile` in both files

**To Reproduce**
1. Build documentation using `make doc`
2. Observe relevant warnings in `../cFS/build/doc/warnings.log`

**Expected behavior**
Functions should be properly documented to avoid warnings

**Reporter Info**
Leor Bleier, NASA GSFC\Code 582

**Comment by CDKnightNASA** [comment]
ref #503 changes
