### ISSUE TITLE
TblHandle used before validation in CFE_TBL_Load

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#687]
**Describe the bug**
TblHandle used before validation

**To Reproduce**
See code snip, invalid handle could cause fault

**Expected behavior**
Validate handle before using

**Code snips**
https://github.com/nasa/cFE/blob/8365a0c69b810e313afe0fe19cdc8987374621e3/fsw/cfe-core/src/tbl/cfe_tbl_api.c#L681-L687

**System observed on:**
In code

**Additional context**
None

**Reporter Info**
Jacob Hageman - NASA/GSFC

**Comment by skliper** [comment]
Ping @dmills3

**Comment by jphickey** [comment]
This isn't really using the table handle - there is no dereferencing of the pointer before validation, so there is no chance of segfault.  Maybe less than ideal form to (possibly) set a pointer to something invalid, but it is not a fault risk.

**Comment by jphickey** [comment]
deleted my previous comment - I see it now ... yes this is a bug.

**Comment by jphickey** [comment]
This code was last modified by @CDKnightNASA in #606 so probably should get his take on best fix.
