### ISSUE TITLE
ut_sb_stubs.c needs a stub for CFE_SB_ZeroCopySend 

### ISSUE THREAD

**Issue by asgibson** [nasa/cFE#703]
**Is your feature request related to a problem? Please describe.**
CFE_SB_ZeroCopySend does not have a stub in ut_sb_stubs.c causing undefined reference error when building unit tests for an app that uses this call.

**Describe the solution you'd like**
Add the stub for CFE_SB_ZeroCopySend with full context tracking.

**Describe alternatives you've considered**
Create my own locally in the app's unit test, but this does not help everyone.

**Requester Info**
Alan Gibson, NASA

**Comment by skliper** [comment]
Can you contribute your implementation?

**Comment by skliper** [comment]
Function deprecated, replaced by `CFE_SB_TransmitBuffer` which has a stub.
