### ISSUE TITLE
ut_sb_stubs.c needs a stub for CFE_SB_DeletePipe 

### ISSUE THREAD

**Issue by asgibson** [nasa/cFE#704]
**Is your feature request related to a problem? Please describe.**
CFE_SB_DeletePipe does not have a stub in ut_sb_stubs.c causing undefined reference error when building unit tests for an app that uses this call.

**Describe the solution you'd like**
Add the stub for CFE_SB_DeletePipe with full context tracking.

**Describe alternatives you've considered**
Create my own locally in the app's unit test, but this does not help everyone.

**Requester Info**
Alan Gibson, NASA

**Comment by skliper** [comment]
@AlanSGibson - we encourage submissions... can you add your implementation to ut_sb_stubs.c and submit a pull request?
