### ISSUE TITLE
Add user-specified extra modules to build system

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#718]
**Is your feature request related to a problem? Please describe.**
As a prerequisite to #554, the user needs to have the ability to specify their own set of extra modules to provide for the features they are customizing.  

**Describe the solution you'd like**
A new setting in `targets.cmake` that allows users to add their own customization layers.

This is similar to but slightly different than loadable apps in that:

- The same set/config should be applied to all CPUs  (i.e. if using for a message abstraction layer, all CPUs should share the same one).  So it belongs as a global setting, rather than a setting associated with a single target.
- These would be linked with cfe core, rather than as dynamically-loaded libraries because something like a message abstraction layer is needed by SB itself, so it can't be loaded later.

**Additional context**
Initial function would be very simple - just include the libraries in the build, nothing more.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment]
Fixed by #751
