### ISSUE TITLE
Remove references to "CCSDS" structures outside of CFE SB. 

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#719]
**Is your feature request related to a problem? Please describe.**
As a prerequisite to #554, all modules other than SB should __NOT__ refer to the "CCSDS" data types and macros.

**Describe the solution you'd like**
Remove references to the `ccsds.h` header file along with any direct references to types defined in this file.  Use the types or abstractions defined in `cfe_sb.h` instead.

**Additional context**
Mostly an issue for the "Send HK" commands that accept a `CCSDS_CommandPacket_t` structure.  

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment]
@jphickey could you prioritize this one?

**Comment by jphickey** [comment]
> @jphickey could you prioritize this one?

Submitted PR, will submit similar issues/PRs for apps too.

**Comment by jphickey** [comment]
FYI: nasa/ci_lab#49, nasa/to_lab#42, nasa/sample_app#69 are the related PRs for the apps.
