### ISSUE TITLE
low CFE_MISSION_MAX_FILE_LEN and CFE_TBL_FILEDEF(..., "sample_app_table.tbl") causes silent non-truncation

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/cFE#730]
**Describe the bug**
I was scratching my head why my table file was named "sample_app_table.tbl\004"  until I realized that CFE_MISSION_MAX_FILE_LEN is defined as "20" and "sample_app_table.tbl" is exactly 20 characters. If I had one more char, the compiler would err. But it accepts static definition of structs using strings that are the exact length, which loses the null terminator.

**Expected behavior**
Should allow file names of CFE_MISSION_MAX_FILE_LEN chars.

**Reporter Info**
Christopher.D.Knight@nasa.gov

**Comment by CDKnightNASA** [comment]
I've pushed an alternative approach of tacking on "\0" to force a compile error if the strlen is the size of the array. Thoughts?

**Comment by ericgilligan-nasa** [comment]
I ran into this exact same issue today. Was scratching my head for a long time on it

**Comment by CDKnightNASA** [comment]
> I ran into this exact same issue today. Was scratching my head for a long time on it

Then you can test out my pull request :D (I seriously forgot to create it.) Note that it's PR #738 that you want to test out...The other PR linked to this was a previous idea that I scrapped, and had accidentally merged in a different branch into the PR branch. Whoop.
