### ISSUE TITLE
CF_ES_StartApplications() uses O_RDONLY instead of OS_READ_ONLY

### ISSUE THREAD

**Issue by MauriceS-gti** [nasa/cFE#752]
**Describe the bug**
Latest OS_open() does not support O_RDONLY flag

**To Reproduce**
Just observation trying to find other bug - no solution for that one yet...

**Expected behavior**
Correct #define use

**Code snips**
If applicable, add references to the software.

**System observed on:**
 - Docker
 - OS: Linux fb2def16b3c1 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Versions [Versions:cFE 6.7.20.0, OSAL 5.0.20.0, PSP 1.4.14.0]

**Additional context**

**Reporter Info**
Maurice Smulders / Geneva Technologies inc

**Comment by jphickey** [comment]
Good find, thanks for noticing/reporting this.  I checked old versions and it appears this has been in there for quite a while, but by luck/chance the `OS_READ_ONLY` and `O_RDONLY` symbols are both defined as zero so it happens to not break it.  

I agree it should use the `OS_READ_ONLY` flag here, not the POSIX flag.
