### ISSUE TITLE
CCSDSv2 MsgId construction not 16 bits as described in cfe_sb_msg_id_util.h

### ISSUE THREAD

**Issue by johnphamngc** [nasa/cFE#781]
**Describe the bug**
CCSDSv2 MsgId construction not 16 bits as described in cfe_sb_msg_id_util.h. It looks like the 8th bit of the APID qualifier subsystem ID is included, making the MsgID 17 bits. 

**To Reproduce**
N/A, code inspection

**Expected behavior**
MsgId should mask off bit 8 in subsystem ID

**Code snips**
https://github.com/nasa/cFE/blob/a47abba14b7e8ffbc8c8e78614babdb151412af2/fsw/cfe-core/src/sb/cfe_sb_msg_id_util.h#L40-L58

https://github.com/nasa/cFE/blob/a47abba14b7e8ffbc8c8e78614babdb151412af2/fsw/cfe-core/src/inc/ccsds.h#L346

https://github.com/nasa/cFE/blob/a47abba14b7e8ffbc8c8e78614babdb151412af2/fsw/cfe-core/src/sb/cfe_sb_msg_id_util.c#L137-L138

**System observed on:**
N/A

**Additional context**
N/A

**Reporter Info**
John N Pham, Northrop Grumman

**Comment by skliper** [comment]
Note that code has a pending PR to fix (#726)... there's also a problem in the APID not being masked, so it could overload the cmd/tlm bit.
