### ISSUE TITLE
Add ES application control API functional tests

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#806]
**Is your feature request related to a problem? Please describe.**
Need open source functional tests for certifiability

**Describe the solution you'd like**
Add functional tests for cFE Application Control APIs
– CFE_ES_RestartApp - Restart a single cFE Application.
– CFE_ES_ReloadApp - Reload a single cFE Application.
– CFE_ES_DeleteApp - Delete a cFE Application.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by nmullane** [comment]
I'll start working on this.
