### ISSUE TITLE
Add cFE ES Information API functional tests

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#808]
**Is your feature request related to a problem? Please describe.**
Need open source functional tests for certifiability

**Describe the solution you'd like**
Add cFE Information API functional tests
– CFE_ES_GetResetType - Return the most recent Reset Type.
– CFE_ES_GetAppID - Get an Application ID for the calling Application.
– CFE_ES_GetAppIDByName - Get an Application ID associated with a specified Application name.
– CFE_ES_GetAppName - Get an Application name for a specified Application ID.
– CFE_ES_GetAppInfo - Get Application Information given a specified App ID.
– CFE_ES_GetTaskInfo - Get Task Information given a specified Task ID.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by wmoleski** [comment]
I am currently working on enhancing Joe Hickey's UT_ASSERT test to implement all of these API calls.

**Comment by skliper** [comment]
Just for fun I was thinking maybe have test logic path where we could execute the first run as power on reset and tests should check everything except what is requires a processor reset... and could set up CDS or whatever... then at the end it could call a power on reset and check the final requirements.  On a system that autoboots this would be easier but on linux could execute from a script.  Just brainstorming.
