### ISSUE TITLE
Deprecate CFE_PLATFORM_CPU_ID, CFE_PLATFORM_CPU_NAME, and CFE_MISSION_SPACECRAFT_ID 

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#827]
**Is your feature request related to a problem? Please describe.**
Got bit by this again (used CFE_MISSION_SPACECRAFT_ID when CFE_PSP_GetSpacecraftId() should have been used).  They also currently return different numbers since the define has historically been 0x42, but the setting in targets.cmake is 42 (decimal).

Related to #710

**Describe the solution you'd like**
Deprecate, actually suggest this error out at compile if defined since it leads to bugs (mismatch of IDs) in favor of CFE_PSP_GetSpacecraftId() and CFE_PSP_GetProcessorId() (and eventually CFE_PSP_GetProcessorName(), See nasa/PSP#165)

**Describe alternatives you've considered**
None.

**Additional context**
#710 

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by CDKnightNASA** [comment]
dumb question, why not `#define CFE_MISSION_SPACECRAFT_ID CFE_PSP_GetSpacecraftId()`?

**Comment by skliper** [comment]
Thought about it, but I didn't think it was worth the bandaid.  Could do it short term while it's deprecated, but not my preference as a permanent solution.  Also might require adding cfe_psp.h depending on what includes are already in.
