### ISSUE TITLE
ES reports version 6.7.0 in telemetry, even when it's built off a development branch

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#830]
**Describe the bug**
Misidentifies version

**To Reproduce**
Look at version in ES housekeeping packet.

**Expected behavior**
System should report a consistent version number at startup, from noops, and in tlm.  Could go back to the old way where development versions all report a revision of 99.

**Code snips**
https://github.com/nasa/cFE/blob/a148b97511de3f45f6677c1a3a0b17197f867e28/fsw/cfe-core/src/es/cfe_es_task.c#L333-L340

**System observed on:**
 - Hardware: cFS Dev Server
 - OS: Ubuntu 18.04
 - Versions: Bundle.

**Additional context**
Got out of sync with new versioning scheme

**Reporter Info**
Jacob Hageman - NASA/GSFC

**Comment by astrogeco** [comment]
Probably should open another one in OSAL
