### ISSUE TITLE
Unsafe macro in cfe_version.h

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#845]
**Is your feature request related to a problem? Please describe.**
Unsafe macro (violates coding standard)

https://github.com/nasa/cFE/blob/06c08268f2d7a7fe72aceec8c33201ce6ccba2f4/fsw/cfe-core/src/inc/cfe_version.h#L48

**Describe the solution you'd like**
Add parentheses

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by skliper** [comment]
Nevermind.  Read up on it, since it quotes it's safe.

**Comment by astrogeco** [comment]
> Nevermind. Read up on it, since it quotes it's safe.

Can you add the stuff you read so we can reference it if it comes up again? I was actually discussing this earlier and wondering if we need to have the integer macros at all. If they're all strings then we wouldn't need the helper functions.

**Comment by skliper** [comment]
My preference is to remove any unused macros!  I just brushed up on the preprocessor macro at https://www.cprogramming.com/reference/preprocessor/stringizing-operator.html, and wrote a quick test program to try and break it and I couldn't (just to confirm it behaved as expected on random strings).
