### ISSUE TITLE
If a message is subscribed, then unsubscribed, additional unsubscribes do not raise error events 

### ISSUE THREAD

**Issue by johnphamngc** [nasa/cFE#862]
**Describe the bug**
If a message is subscribed, then unsubscribed, additional unsubscribes do not raise error events 

**To Reproduce**
Have SB subscribe to a message
Have SB unsubscribe to that message
Have SB unsubscribe again to that message

**Expected behavior**
Event message should be raised

**Code snips**
https://github.com/nasa/cFE/blob/08f6eab17702eac689a468974a32af8d41d4362a/fsw/cfe-core/src/sb/cfe_sb_api.c#L1059-L1112

If a message was previously subscribed to, and all pipes subscribing to it were subsequently unsubscribed, and an additional unsubscribe is issued, a valid routing index would still exist in the msgmap table, and thus an error event would not be raised.

**System observed on:**
N/A, discovered via code inspection

**Additional context**
N/A

**Reporter Info**
John N Pham, Northrop Grumman

**Comment by CDKnightNASA** [comment]
This is likely a side-effect of a fix I implemented in #101

**Comment by skliper** [comment]
Yeah, actually looks to me like this will seg fault (tries to access NULL pointer).  Note I'd like to add this as a test scenario to the new functional test framework (part of subscribe/unsubscribe API testing).

**Comment by CDKnightNASA** [comment]
> Yeah, actually looks to me like this will seg fault (tries to access NULL pointer). Note I'd like to add this as a test scenario to the new functional test framework (part of subscribe/unsubscribe API testing).

I'm re-designing; can you point at the line you expect a seg fault?

**Comment by skliper** [comment]
I don't think 1078 is true now, so 1083 will == NULL, and any of the following references to it would fault.  Didn't test, but that's what it looks like to me upon inspection.

https://github.com/nasa/cFE/blob/08f6eab17702eac689a468974a32af8d41d4362a/fsw/cfe-core/src/sb/cfe_sb_api.c#L1078-L1083

**Comment by CDKnightNASA** [comment]
> I don't think 1078 is true now, so 1083 will == NULL, and any of the following references to it would fault. Didn't test, but that's what it looks like to me upon inspection.
> 
> https://github.com/nasa/cFE/blob/08f6eab17702eac689a468974a32af8d41d4362a/fsw/cfe-core/src/sb/cfe_sb_api.c#L1078-L1083

Ah, yes...I am guessing RoutePtr will always be != NULL, but ListHeadPtr could be NULL and yes line 1087 would segfault. My redesign avoids this.
