### ISSUE TITLE
Add unsubscribe test case to cover #862

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#873]
**Is your feature request related to a problem? Please describe.**
#862 looks like it could have resulted in a seg fault, fixed in #865
 Unsubscribe after no subscriptions are left...

**Describe the solution you'd like**
Add test case.

**Describe alternatives you've considered**
None.  Should add test to confirm code works.

**Additional context**
#862 #865 

**Requester Info**
Jacob Hageman - NASA/GSFC
@CDKnightNASA

**Comment by CDKnightNASA** [comment]
Looks like current tests hits it ... lcov report shows that lines 1102-1110 were covered one time. But I will assume you mean that you'd like an explicit test.

**Comment by skliper** [comment]
Note `Test_Unsubscribe_NoMatch) doesn't actually unsubscribe from MsgId or SB_UT_TLM_MID1, so it's not checking the unsubscribe followed by unsubscribe case.  The test modifies the PipeId for the MsgId description such that it won't unsubscribe.  I had to dig a bit since the test is light on comments as to the "why"...

https://github.com/nasa/cFE/blob/be1a23a8b32b6ecd03053d6924bb152d08b0c61b/fsw/cfe-core/unit-test/sb_UT.c#L2520-L2544
