### ISSUE TITLE
CFE_MISSION_REV defined in 2 locations

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#877]
**Describe the bug**
CFE_MISSION_REVE defined in 2 locations

**To Reproduce**
Inspection

**Expected behavior**
Define in 1 location... if it's for clone and own, version seems to make sense... if it includes configuration versioning then useful in the config file.

**Code snips**
https://github.com/nasa/cFE/blob/db829294eba01b88683e679d58435f65ca02f826/cmake/sample_defs/cpu1_platform_cfg.h#L1797
https://github.com/nasa/cFE/blob/db829294eba01b88683e679d58435f65ca02f826/fsw/cfe-core/src/inc/cfe_version.h#L46

**System observed on:**
N/A

**Additional context**
None

**Reporter Info**
Jacob Hageman - NASA/GSFC

**Comment by skliper** [comment]
Need a decision on resolution approach.

**Comment by jphickey** [comment]
FWIW I don't think either of these are correct - it should be in `cfe_mission_cfg.h` ...

I think the one in `cpu1_platform_cfg.h` is probably a mistake ... that file is only supposed to be platform stuff, not mission stuff.  And missions shouldn't be changing stuff directly in the CFE source code.

**Comment by astrogeco** [comment]
I support it from `version.h` we'd need to apply this to all components though.

**Comment by skliper** [comment]
If they are changing it though, most likely it's due to changing CFE source code already so I don't have a strong objection to just leaving it in the header file...  It's for the clone-and-own types, not really intended for configuration versioning as far as I can tell.  If it was configuration versioning, I'd expect it to be platform specific...

**Comment by skliper** [comment]
CCB - 2020-09-23: remove from the config, treat this as the number that "projects" get to update as the version number.  Leave in version.h got at least 2 votes.
