### ISSUE TITLE
Compiling for Raspberry Pi

### ISSUE THREAD

**Issue by aFunnyBit** [nasa/cFE#9]
Would like to run on my ARM based raspberry pi, the instructions don't seem to detail a means of building for different arch.

Thanks

**Comment by the-other-james** [comment]
Hi @aFunnyBit, it is possible either cross-compile cFE for or compile cFE on a Raspberry Pi. However, this repository isn't really intended to have instructions for setting cFE up on every target (but if you find a good tutorial, please let me know).

For this type of question, I would like to direct you to the community Q&A site and forums. Someone previously posted about an issue they had [compiling OSAL for the Pi](http://coreflightsystem.org/questions/question/compiling-for-raspberry-pi-2). There is also a discussion on the [forum](http://coreflightsystem.org/forums/topic/cubesatsraspberry-pi/).
