### ISSUE TITLE
Move typedefs used in cmd/tlm to the *_msg.h file

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#909]
**Is your feature request related to a problem? Please describe.**
CFE_ES_AppInfo_t and CFE_ES_MemHandle_t are defined in cfe_es.h, but used in telemetry (cfe_es_msg.h).  All the typedefs used in telemetry should be defined in the *_msg.h file.

**Describe the solution you'd like**
Move CFE_ES_AppInfo_t and CFE_ES_MemHandle_t into cfe_es_msg.h

Note CFE_ES_TaskInfo_t is not used in cmd/tlm.

**Describe alternatives you've considered**
None

**Additional context**
Related to #899

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
I'd like to move this definition after review/merge of #917, as this changes `CFE_ES_MemHandle_t`.

Once decided (along with #913) then I suggest that the handle/resourceid types go into `cfe_es_extern_typedefs.h` and the structures go into `cfe_es_msg.h`.
