### ISSUE TITLE
remove "SenderReporting" from SB private "global"

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/cFE#933]
The SenderReporting field exists in the SB global struct but is only set once and never used.

https://github.com/nasa/cFE/blob/8a7dc8f2e434889287973c41d4a5cb4a48f48b44/fsw/cfe-core/src/sb/cfe_sb_priv.h#L285

**Comment by jwilmot** [comment]
FYI, this was part of SB and SBN at least up to 2013.  It was intended for last sender, local and over SBN. It was added DCR469:1 Added GetLastSender code ** Revision 1.68 2007/04/24 11:07:18EDT
Not sure who took it out or why. Too late for this now.
From cfe_sb_api.c
/* store the sender information /
if(CFE_SB.SenderReporting != 0)
{
if (SenderPtr == NULL) { / This is a normal SB send call /
BufDscPtr->Sender.ProcessorId = CFE_PSP_GetProcessorId();
strncpy(&BufDscPtr->Sender.AppName[0],CFE_SB_GetAppName(TskId,FullName),OS_MAX_API_NAME);
}
else { / Caller wants to set the Sender metadata (Likely an SBN call) */
BufDscPtr->Sender.ProcessorId = SenderPtr->ProcessorId;
strncpy(&BufDscPtr->Sender.AppName[0], &SenderPtr->AppName[0], OS_MAX_API_NAME);
}

}
