### ISSUE TITLE
Doxygen description of stub for CFE_SB_SendMsg is not correct

### ISSUE THREAD

**Issue by asgibson** [nasa/cFE#938]
**Describe the bug**
Description on the stub for CFE_SB_SendMsg is out of date.

**Expected behavior**
Update description

**Code snips**
https://github.com/nasa/cFE/blob/8a7dc8f2e434889287973c41d4a5cb4a48f48b44/fsw/cfe-core/ut-stubs/ut_sb_stubs.c#L453-L462

**Reporter Info**
Alan Gibson  NASA GSFC/587

**Comment by skliper** [comment]
Stub deprecated in #1015, `CFE_SB_TransmitMsg` stub is documented correctly.
