### ISSUE TITLE
CFE_PLATFORM_ES_PERF_MAX_IDS not fully deprecated

### ISSUE THREAD

**Issue by pchapates** [nasa/cFE#945]
**Describe the bug**
CFE_PLATFORM_ES_PERF_MAX_IDS was superseded by CFE_MISSION_ES_PERF_MAX_IDS as noted in this comment: https://github.com/nasa/cFE/search?q=CFE_PLATFORM_ES_PERF_MAX_IDS. However, sample cpu1_platform_cfg.h still contains the definition for CFE_PLATFORM_ES_PERF_MAX_IDS is still referenced in es_UT.c and comments in cfe_es_events.h and sample_perfids.h

**To Reproduce**
N/A

**Expected behavior**
Either CFE_PLATFORM_ES_PERF_MAX_IDS should be totally deprecated and all references should be replaced by CFE_MISSION_ES_PERF_MAX_IDS or (if deemed necessary) support for platform-specific max values should be re-added in the perf-log implementation.

**Code snips**
cfe/cmake/sample_defs/cpu1_platform_cfg.h:1978
cfe/fsw/cfe-core/src/inc/cfe_es_events.h:1046
cfe/fsw/cfe-core/unit-test/es_UT.c:3664

**System observed on:**
N/A

**Additional context**
N/A

**Reporter Info**
PJ Chapates Gateway Vehicle System Manager FSW Production, JSC

**Comment by jphickey** [comment]
CCB topic - 

For this we need to decide if its worth having a (potentially) lower PLATFORM limit vs the MISSION limit.   For instance, one can set `CFE_PLATFORM_ES_MAX_APPLICATIONS` lower than `CFE_MISSION_ES_MAX_APPLICATIONS` which can save memory on a local processor while still keeping telemetry packet sizes consistent across all CPUs.  There may be a valid reason to implement a similar thing for perfids too.

That will determine whether this goes away completely or it gets reinstated as the size of internal tables.

**Comment by skliper** [comment]
CCB: 2020-10-14 - Discussion: mission sizes telemetry, the platform version could size memory footprint.  This isn't a requirement at this point so the path forward is to just remove the platform defines, open an optional ticket that covers the potential to reduce memory footprint (not targeted to a build.)

**Comment by skliper** [comment]
> [CCB: 2020-10-14](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-October-14-2020) - Discussion: mission sizes telemetry, the platform version could size memory footprint. This isn't a requirement at this point so the path forward is to just remove the platform defines, open an optional ticket that covers the potential to reduce memory footprint (not targeted to a build.)

See #1103 for the new issue
