### ISSUE TITLE
UT checking calls to OS_printf

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#955]
**Is your feature request related to a problem? Please describe.**
Many unit tests are checking the calls to `OS_printf()`.  But typically all syslog/printf type messages are not fulfilling any sort of requirements, they are just informational in nature.  

So AFAIK there isn't really a strong justification to specifically check for certain syslog messages, but the fact that the UT does check for these means that any time the syslog messages are changed or refactored in any way, one gets a bunch of nuisance UT failures.  As a result we spend a lot of time fixing UT tests for things that aren't really relevant to the operation of the code.

**Describe the solution you'd like**
At least remove checks for number of times `OS_printf()` was called in a given path.  This is really quite irrelevant to pass/fail. 

The `UT_PrintfIsInHistory` tests might be OK to keep, but an actual return code should be preferred.  If there is no return code then this is probably OK - its also less volatile because it just checks format string and confirms that a specific path was taken.

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by CDKnightNASA** [comment]
Agreed!
