### ISSUE TITLE
CFE_ES_CDSRegDumpRec_t has implicit padding

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#966]
**Is your feature request related to a problem? Please describe.**
Related to #664 - implicit padding should be avoided

**Describe the solution you'd like**
Eventually pack definitions will come from a common definition, with explicit padding

**Describe alternatives you've considered**
None

**Additional context**
Observed in testing Bootes

**Requester Info**
Jacob Hageman - NASA/GSFC

@wmoleski

**Comment by jphickey** [comment]
Actually I noticed this as part of #909 because this structure is used for data files (and therefore should be included in the msg structs as it is part of the interface) and fixed it as part of that change.

**Comment by jphickey** [comment]
Checked again - there is one more thing needed here.  Previous change fixed the name length to use mission-scope definition which is a multiple of 4, fixing that part of the problem, but there is still a padding due to the use of a `bool` value (1 byte) - so the alignment does need adjustment.
