### ISSUE TITLE
Sample Config Leap Seconds needs update

### ISSUE THREAD

**Issue by zanzaben** [nasa/cFE#983]
**Describe the bug**
The sample configuration's CFE_MISSION_TIME_DEF_LEAPS was set to 32 and should currently be 37

**To Reproduce**
Visual inspection

**Expected behavior**
CFE_MISSION_TIME_DEF_LEAPS should be 37 

**Code snips**
https://github.com/nasa/cFE/blob/e0d1ce883476931c86adc00adac49edea1a30d5a/cmake/sample_defs/sample_mission_cfg.h#L176

**System observed on:**
N/A 

**Additional context**
#187 

Leap Second History
https://www.nist.gov/pml/time-and-frequency-division/time-services/nist-time-scale-data-archive

**Reporter Info**
Alex Campbell NASA GSFC

**Comment by astrogeco** [comment]
Edit: Added Leap second NIST table to "addditional context" section
